// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by src/web_assets/wizard/gen_theme_blobs.py - DO NOT EDIT BY HAND.
// Add or edit a theme under src/web_assets/themes/ and re-run the generator.

/**
 * @file binary_asset_blobs.h
 * @brief Layer 7 - toggleable embedded theme stylesheets (PROTOCORE_ENABLE_THEMES).
 *
 * A registry of minified CSS themes in flash (DROM), for serving/switching a theme at runtime.
 * Behind PROTOCORE_ENABLE_THEMES so a build that does not want it links nothing.
 */

#ifndef PROTOCORE_BINARY_ASSET_BLOBS_H
#define PROTOCORE_BINARY_ASSET_BLOBS_H

#include "protocore_config.h"

#if PROTOCORE_ENABLE_THEMES

#include <stddef.h>

/** @brief One embedded theme: its name and its minified CSS (NUL-terminated flash string). */
struct protocore_theme_blob
{
    const char *name;
    const char *css;
};

/** @brief The embedded theme registry (sorted by name) and its count. */
extern const protocore_theme_blob PROTOCORE_THEME_BLOBS[];
extern const size_t PROTOCORE_THEME_BLOB_COUNT;

/**
 * @brief Look up a theme's CSS by name (exact match).
 * @return the NUL-terminated minified CSS, or nullptr if no theme by that name is embedded.
 */
const char *protocore_theme_css(const char *name);

#endif // PROTOCORE_ENABLE_THEMES
#endif // PROTOCORE_BINARY_ASSET_BLOBS_H
