// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by src/web_assets/wizard/build_assets.py - DO NOT EDIT BY HAND.
// Edit the source documents under src/web_assets/input/ and re-run the generator.

/**
 * @file web_assets.h
 * @brief Layer 7 (Application) - embedded web assets generated from src/web_assets/input/.
 *
 * One declaration per source document under src/web_assets/input/ (its base name is the
 * C symbol). On ESP32 these const arrays live in flash (DROM), read directly - no
 * filesystem or heap. Edit src/web_assets/input/ and re-run src/web_assets/wizard/build_assets.py.
 */

#ifndef PROTOCORE_WEB_ASSETS_H
#define PROTOCORE_WEB_ASSETS_H

// ---- html ----
/** @brief Real-time SVG telemetry dashboard page (PROTOCORE_ENABLE_DASHBOARD). */
extern const char PC_DASHBOARD_PAGE[];

/** @brief Captive-portal form for WiFi credential entry (provisioning service). */
extern const char PC_PROV_FORM[];

/** @brief Success page shown after credentials are saved and the device reboots. */
extern const char PC_PROV_SAVED_HTML[];

/** @brief Self-contained WebSocket terminal page (green-phosphor CRT theme; auto ws/wss). */
extern const char PC_TERMINAL_PAGE[];

// ---- js ----
/** @brief Service worker: precaches the app shell from the versioned manifest and serves it stale-while-revalidate. */
extern const char PC_SERVICE_WORKER[];

// ---- json ----
/** @brief Runtime stats JSON (rendered via send_template); add/rename fields to taste. */
extern const char PC_STATS_JSON[];

// ---- text ----
/** @brief All available Prometheus metrics; comment a value line out with a leading # to drop it. */
extern const char PC_METRICS_PROM[];

#endif // PROTOCORE_WEB_ASSETS_H
