#!/usr/bin/env python3
# ProtoCore v1.0.16 - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate the example index in docs/EXAMPLES.md from the examples/ directory.

The prose (intro, build-and-run, troubleshooting) is hand-maintained; the per-group
lists of examples and the total count are generated by scanning `examples/`, so they
can never drift from the tree (they had - the Foundation group silently lost 16
entries before this existed). Each group dir is listed in order as a collapsible
section carrying its layer badge and example count, its example dirs sorted
alphabetically into a grid.

Run from the repo root:
    python -m tools.ci_tooling.generate.gen_examples            # rewrite the index
    python -m tools.ci_tooling.generate.gen_examples --check    # CI: fail if stale
"""

import os
import sys

from tools.ci_tooling.lib import doc_region as dr

ROOT = dr.repo_root(__file__)
EXAMPLES_DIR = os.path.join(ROOT, "examples")
EXAMPLES_MD = os.path.join(ROOT, "docs", "EXAMPLES.md")

# Link each example to its README, relative: on github.com the README renders in place, and
# Doxygen (which now takes examples/**/README.md as input, see docs/Doxyfile) resolves the same
# relative link to the rendered Pages page. So the walkthroughs live ON the site, not as bare
# repo links. Each README documents its example directory, so the pages nest under the Files
# tree by path (no nav-root flood); this index just links them by OSI-layer group.

REGION = dr.Region(EXAMPLES_MD, "EXAMPLE INDEX", dr.tool_id(__file__))

# Ordered groups: (directory name, heading, badge, one-line description).
#
# The badge is the structural device in the index, so it has to be true: the OSI groups
# carry their real layer number, and the three that are not layers say what they actually
# are rather than being handed a number to make the set look tidy.
GROUPS = [
    (
        "Foundation",
        "Foundation",
        "CORE",
        "Start here: the core tutorial path (Basic -> Advanced -> Expert -> Sysadmin -> "
        "Configuration), then the server-architecture examples - the preempting task queue, "
        "lanes, and interface forwarding:",
    ),
    (
        "Peripherals",
        "Peripherals",
        "HW",
        "On-chip and add-on interface hardware - Ethernet (internal + W5500), CAN, Wi-Fi " "capture, and DMA ingest:",
    ),
    (
        "Drivers",
        "Drivers",
        "HW",
        "External chip drivers over I2C / SPI / UART - sensors, ADC / PWM / current monitors, "
        "an RTC, and radio-module gateways:",
    ),
    ("L4-Transport", "Transport", "L4", "Connections, encryption, and flood defense:"),
    ("L5-Session", "Session", "L5", "Interactive consoles:"),
    ("L6-Presentation", "Presentation", "L6", "Parsing, codecs, auth, WebSocket/SSE:"),
    ("L7-Application", "Application", "L7", "Routing, protocols, services, and clients:"),
]


def examples_in(group_dir):
    """Return the example dirs under a group (each holds a README.md), sorted alphabetically.

    Alphabetical (case-insensitive) gives a deterministic, filesystem-independent order so the
    CI --check never diverges from a local regen by readdir order.
    """
    path = os.path.join(EXAMPLES_DIR, group_dir)
    names = [
        n
        for n in os.listdir(path)
        if os.path.isdir(os.path.join(path, n)) and os.path.isfile(os.path.join(path, n, "README.md"))
    ]
    return sorted(names, key=str.lower)


def build_index():
    """Return (region body, total example count). Markers are added by dr.apply.

    Emits @subpage, not a plain link. Doxygen parks a markdown page at the nav ROOT unless
    another page claims it, so plain links left all 152 examples at the top level - 152 of
    the tree's 197 root entries, which is why the sidebar had no usable categories. @subpage
    renders the same link and also nests the page under this index.

    The items must be markdown for @subpage to be seen, so they sit as markdown inside the
    HTML wrapper with blank lines around them - that is how Doxygen re-enters markdown.
    """
    parts = ['<div class="pc-examples">', ""]
    total = 0
    for group_dir, heading, badge, desc in GROUPS:
        names = examples_in(group_dir)
        total += len(names)
        # Foundation is the tutorial path - the one group a first-time reader wants open.
        open_attr = " open" if group_dir == "Foundation" else ""
        parts += [
            f"<details{open_attr}>",
            # Plain text with a literal middle dot: Doxygen strips <span> inside <summary>
            # (which collapsed
            # "CORE Foundation 9" into "COREFoundation9".
            f"<summary>{badge} · {heading} · {len(names)} examples</summary>",
            "",
            f'<p class="pc-desc">{desc}</p>',
            "",
        ]
        for n in names:
            # Doxygen's auto id for a markdown page is its path with / replaced by _2.
            # Hyphens are NOT escaped: examples/L4-Transport/X/README.md is
            # md_examples_2L4-Transport_2X_2README (verified against the generated files).
            page_id = f"md_examples_2{group_dir}_2{n}_2README"
            parts.append(f'- @subpage {page_id} "{n}"')
        parts += ["", "</details>", ""]
    parts.append("</div>")
    return "\n".join(parts), total


def main():
    check = "--check" in sys.argv[1:]
    body, total = build_index()

    # The example count also appears in prose OUTSIDE the region. It used to be
    # patched with re.sub(count=1), which silently left the number stale if that
    # sentence was ever reworded; re_sub_once fails instead.
    def patch_count(text):
        return dr.re_sub_once(
            text, r"ships \d+ runnable examples", f"ships {total} runnable examples", "example count in prose"
        )

    return dr.apply(EXAMPLES_MD, {REGION: body}, check=check, transform=patch_count)


if __name__ == "__main__":
    main()
