// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Unit tests for the OIDC RS256 ID-token verifier (services/security/oidc). Vectors are
// real RSA-2048 tokens signed with openssl (scratchpad/gen_oidc.sh); the JWKS
// carries the matching public key (n, e). Exercises the happy path, claim
// extraction, aud-as-array, and every rejection (alg, signature, iss, aud, exp,
// missing key, malformed).

#include "core_setup/hal/nvs.h"       // the host key is provisioned the way a board's is
#include "crypto/asymmetric/bignum.h" // bn_* direct coverage
#include "mmgr/plaintext.h"
#include "network_drivers/tls/ssh_rsa.h" // in-test RS256 signing
#include "services/security/oidc/oidc.h"
#include "test/fixtures/ssh_test_host_key/ssh_test_keys.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <unity.h>

static uint8_t tw[4096]; // test-side working bytes for the crypto entry points

// Provisions the host key so a test can mint RS256 tokens with arbitrary claims and exercise the
// post-signature-verify guards. Defined below, used before it.
static void setup_rt_key(pc_oidc_key *key);

// A known RSA-2048 keypair (same as test_ssh_crypto's round-trip fixture).
static const char RT_N[] = "a855616bbe1ed8ff73463006a1c2e9fcb67d8b3f39e19df514bd17f444697402"
                           "52d7e059497714b436fdabfc56a75a09ce85f9946f2896cd57e705a7d432a89c"
                           "c2296ad8e04b12e26648279c203cbfe4e0784a0dc4be8b370abf02c126f87aa3"
                           "7860267f4b11b49fcc00d830b45fc2fb5ded85ddcbe684201ed7c614de313ead"
                           "2410bc0ef689cc32909159f6c29279075c4bbf43deea939b32901a93c1bcb38c"
                           "528253951433076c1a3b9864e9d95f04c3757634a8626cae7826f501a2f20288"
                           "6eb4b63fc27b1bff84bafb4be5b4d1bc603e1c711112dc318a5213e7c2a71d49"
                           "6935767aec1dcd5e46f3d159f51daf8525e3b78833f561af2e34a2698539c58f";
static const char RT_D[] = "0568149fe10fdd01f242187e5ce4b3435f90d88f98611ccce2fdb4aa2edd2ec8"
                           "792dfb1f7c2bc999850d352991045c95530d254159dea2f0be78614b7abaa617"
                           "511f279206aac4e74a7efea4fa705fec97ea82dcac34888492d7ffdc93e15a7e"
                           "749eacd26f6706adeb8441ffa02ee80ff37c4996c508b4921bd259a322f26264"
                           "204e74612f1e58b1b5c54507a01916751dfcac4ed30aade8a0e458d2d636a35a"
                           "1f309e7bec81b348aa603b14be4c8dfc4dc2b5693fdfa1c1227ad33999c2f4d1"
                           "5f6ecea9d3fdb3337c31a11eb498f30c2b47ad9fcff3a68240e23595e406ceb4"
                           "ba73c3d29a97a67517ca45ae871673ca769cdf627a72ccd8b7bb3d57a195c3b5";

static void hex2bytes(uint8_t *out, const char *hex, size_t n)
{
    for (size_t i = 0; i < n; i++)
    {
        char b[3] = {hex[2 * i], hex[2 * i + 1], 0};
        out[i] = (uint8_t)strtol(b, NULL, 16);
    }
}

static const char B64URL[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
static size_t b64url_enc(const uint8_t *in, size_t n, char *out)
{
    size_t o = 0;
    for (size_t i = 0; i < n; i += 3)
    {
        int rem = (int)(n - i);
        uint32_t v = (uint32_t)in[i] << 16;
        if (rem > 1)
        {
            v |= (uint32_t)in[i + 1] << 8;
        }
        if (rem > 2)
        {
            v |= in[i + 2];
        }
        out[o++] = B64URL[(v >> 18) & 63];
        out[o++] = B64URL[(v >> 12) & 63];
        if (rem > 1)
        {
            out[o++] = B64URL[(v >> 6) & 63];
        }
        if (rem > 2)
        {
            out[o++] = B64URL[v & 63];
        }
    }
    out[o] = '\0';
    return o;
}

// Mint a valid RS256 JWT for the given payload JSON, signed with the RT private key.
static void make_jwt(const char *payload_json, char *tok, size_t tok_cap)
{
    static const char HDR[] = "{\"alg\":\"RS256\"}";
    char seg0[64], seg1[512], signing[600], seg2[400];
    b64url_enc((const uint8_t *)HDR, strlen(HDR), seg0);
    b64url_enc((const uint8_t *)payload_json, strlen(payload_json), seg1);
    int sl = snprintf(signing, sizeof(signing), "%s.%s", seg0, seg1);
    uint8_t sig[256];
    ssh_rsa_sign(tw, (const uint8_t *)signing, (size_t)sl, PC_RSA_HASH_SHA256, sig); // RS256 = SHA-256
    b64url_enc(sig, 256, seg2);
    snprintf(tok, tok_cap, "%s.%s.%s", seg0, seg1, seg2);
}

// --- generated by gen_oidc.sh (RSA-2048, RS256) ---
static const char *K_TOK_VALID =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2V5LTEifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlIiwiYXVkIj"
    "oiY2xpZW50LTEyMyIsInN1YiI6InVzZXItNDIiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjQxMDI0"
    "NDQ4MDB9.QBKta3RxQh8K5FiNUL6ZJemBvIGmDsgZFhF5FbEkjcmbgNsbPZsLl70N0UFwGbsAY5sGoUZxPhWdl-_VT2nXQnwbCVqIrztVibBj4wlwL"
    "e_jY28M5OLf9t3mT5YaxWmV2FWUS_2yTYBEY96CweeoEeX_oSUSOJZyxZ_e8vbET9RcQU4zSx1sDwK6X9dUHZvs8QmrVCdqFP3OAUq0aqguj87Wcor"
    "YvCmB8nBVwYqmNupvRPP8bBPh9nTISEkP6uTQKVJKrnp5C6JN2puWS06G-YzX6HJW3nS2lHj3iI7_6xqD_pI0eXh720ZwzYSK6PPbn9EHiiw0WuaBt"
    "6G9QwR-Rg";
static const char *K_TOK_EXPIRED =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2V5LTEifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlIiwiYXVkIj"
    "oiY2xpZW50LTEyMyIsInN1YiI6InVzZXItNDIiLCJpYXQiOjE1MDAwMDAwMDAsImV4cCI6MTYwMDAwMDAwMH0.maHZCcdhtKEyDG_VI55NPIQ9V8FX"
    "up9bm4-2Iylx8UGBSHIEm9AJcivxjU4mjgulmb6KW2mX7wPbEPf24p5r-vysJxNLcdItyZfFUy8opB_cF3HC_XYPibqgTf80CuYPJ5acKEoaVHNO7m"
    "9J66GFpmfFn02yL6EtacfZRkKvjEwXhVKfPsMmklLv5n4zSxNkwXkQSqm7SH9xoz3ohNWBNkglNMF-kNOC9jWWKdL58GTvecPKog43wVa9j_kS0VM8"
    "NAwihLbFAKQjSJF6bcX5yZsyYUVxtKDXP8WZnEQbsG122_xFZ6vrul4ZOtsH72J2OYK-6ilfaSEenE2cVudPvw";
static const char *K_TOK_AUDARR =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2V5LTEifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlIiwiYXVkIj"
    "pbIm90aGVyLWFwcCIsImNsaWVudC0xMjMiXSwic3ViIjoidSIsImlhdCI6MTcwMDAwMDAwMCwiZXhwIjo0MTAyNDQ0ODAwfQ.O0aL542aHac3DGg6"
    "2u_OmNww5Whfu-tmYIFUosW9p0bTFFa9hywtf77qkz039y-Sirj7KjUINUK7o_8U6BuLlaX0EdG0M6iBO4rs7NZo2vEP5t2yd9j9Cp9hwvkBulfCrC"
    "nHiBTEc06HXRva1ocYcQ5xcrEkY1JNPeALgIIpHyAJpwm5mGaMm04cTFEdshbBwoSpKaCnwKGEXZm8gMJDBmMlGbXZ2f3rLmxXPlo53KN2wVMvnSF-"
    "MD9O9Qwton1psUH_IJQsFrqoABXL1wc4cCmEpdeTEJtkV0uWWzgF825wl6v1KhUtxZojGHtZXf9PpH_PtGMuROGqHkid5drHKA";
static const char *K_TOK_HS256HDR =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2V5LTEifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlIiwiYXVkIj"
    "oiY2xpZW50LTEyMyIsInN1YiI6InVzZXItNDIiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjQxMDI0"
    "NDQ4MDB9.AAAA";
static const char *K_JWKS =
    "{\"keys\":[{\"kty\":\"RSA\",\"use\":\"sig\",\"kid\":\"test-key-1\",\"alg\":\"RS256\","
    "\"n\":\"owVI9J0dgUuZi6j45vERbQdj4OuB7vY-o7k6IWGdckzCfaNaeEdbaCvK7j2OpEKyKWHsgYAcqQJXbSCnQQuIvbJPNJu8iWAqwZsakKmS0Y"
    "0aP9HIaPvlMi8pN6ihVH8lutfeWVwhn-5_V_4Y5UWRJSzZXNUplH5TML2fVWlkU1XqkbZVnkyrAqK4N8ic1Is80g4JDJvMWNRR2cltCj1hjudBiLza"
    "xwCMRp6lvXV0YsYUL-Hw3gFSSDp4MiH0zkvivV1t3qq8OG9tBUcvZtrW0D7f5FP2YqV30XJko1PaCfnwl3KsiJwno4wK0hybd9ujjDSLW7DhKE88oC"
    "W0Y8YMRQ\",\"e\":\"AQAB\"}]}";

static const char *ISS = "https://issuer.example";
static const char *AUD = "client-123";
static const uint32_t NOW = 1700000100; // after iat(1700000000), before exp(4102444800)

void setUp()
{
}
void tearDown()
{
}

// JSON-parse edge guards reachable before signature verify (header parse), plus the
// scratch-exhaustion fail-closed and a JWK whose modulus decodes to nothing.
void test_oidc_parse_edge_guards()
{
    pc_oidc_key key;
    key.loaded = PROTO_FALSE;
    TEST_ASSERT_TRUE(pc_oidc_jwks_find(K_JWKS, "test-key-1", &key));

    // Crafted headers whose "alg" value trips a find_field edge (before sig verify) -> ERR_ALG:
    // a value missing after ':', an unterminated array value, and a numeric value.
    const char *hdr_colon = "eyJhbGciOg.b.c";      // {"alg":
    const char *hdr_array = "eyJhbGciOlthYmM.b.c"; // {"alg":[abc
    const char *hdr_negnum = "eyJhbGciOi01fQ.b.c"; // {"alg":-5}
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_ALG,
                          pc_oidc_verify_with_key(hdr_colon, strlen(hdr_colon), &key, ISS, AUD, NOW, NULL));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_ALG,
                          pc_oidc_verify_with_key(hdr_array, strlen(hdr_array), &key, ISS, AUD, NOW, NULL));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_ALG,
                          pc_oidc_verify_with_key(hdr_negnum, strlen(hdr_negnum), &key, ISS, AUD, NOW, NULL));

    // Scratch arena exhausted before the decode buffers can be borrowed -> fail closed.
    pc_plaintext_reset();
    while (pc_plaintext_alloc(256, 1))
    {
    }
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT,
                          pc_oidc_verify_with_key(K_TOK_VALID, strlen(K_TOK_VALID), &key, ISS, AUD, NOW, NULL));
    pc_plaintext_reset();

    // A JWK whose modulus base64url-decodes to nothing -> parse_rsa_jwk fails.
    static const char *K_JWKS_BADN = "{\"keys\":[{\"kty\":\"RSA\",\"kid\":\"bad\",\"n\":\"\",\"e\":\"AQAB\"}]}";
    pc_oidc_key bad;
    bad.loaded = PROTO_FALSE;
    TEST_ASSERT_FALSE(pc_oidc_jwks_find(K_JWKS_BADN, "bad", &bad));
}

// Guards that run only after the signature verifies: minted (validly-signed) tokens with
// custom claims exercise the aud-missing / aud-array / not-yet-valid / empty-payload paths.
void test_oidc_signed_claim_guards()
{
    pc_oidc_key key;
    setup_rt_key(&key);

    char tok[2048];
    const char *II = "https://issuer.example";

    // No `aud` member at all -> aud_contains find_field fails -> ERR_AUD.
    char pl[256];
    snprintf(pl, sizeof(pl), "{\"iss\":\"%s\",\"exp\":4102444800}", II);
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_AUD, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));

    // aud is an array with no matching entry -> the array loop finds no match -> ERR_AUD.
    snprintf(pl, sizeof(pl), "{\"iss\":\"%s\",\"aud\":[\"other-app\"],\"exp\":4102444800}", II);
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_AUD, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));

    // aud array whose entry has an unterminated quote -> the inner scan bails -> ERR_AUD.
    snprintf(pl, sizeof(pl), "{\"iss\":\"%s\",\"aud\":[\"x],\"exp\":4102444800}", II);
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_AUD, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));

    // A token whose nbf is in the future -> ERR_NOT_YET.
    snprintf(pl, sizeof(pl), "{\"iss\":\"%s\",\"aud\":\"%s\",\"exp\":4102444800,\"nbf\":4102444800}", II, AUD);
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_NOT_YET, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));

    // A valid signature over a payload segment that base64url-decodes to nothing -> ERR_FORMAT.
    {
        static const char HDR[] = "{\"alg\":\"RS256\"}";
        char seg0[64], signing[128], seg2[400];
        b64url_enc((const uint8_t *)HDR, strlen(HDR), seg0);
        int sl = snprintf(signing, sizeof(signing), "%s.A", seg0); // payload segment "A" decodes to 0 bytes
        uint8_t sig[256];
        ssh_rsa_sign(tw, (const uint8_t *)signing, (size_t)sl, PC_RSA_HASH_SHA256, sig); // RS256 = SHA-256
        b64url_enc(sig, 256, seg2);
        snprintf(tok, sizeof(tok), "%s.A.%s", seg0, seg2);
        TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));
    }
}

void test_token_kid()
{
    char kid[64];
    TEST_ASSERT_TRUE(pc_oidc_token_kid(K_TOK_VALID, strlen(K_TOK_VALID), kid, sizeof(kid)));
    TEST_ASSERT_EQUAL_STRING("test-key-1", kid);
}

void test_jwks_find()
{
    pc_oidc_key key;
    key.loaded = PROTO_FALSE;
    TEST_ASSERT_TRUE(pc_oidc_jwks_find(K_JWKS, "test-key-1", &key));
    TEST_ASSERT_TRUE(key.loaded);
    // e = AQAB = 65537 -> 0x00 0x01 0x00 0x01 right-aligned.
    TEST_ASSERT_EQUAL_HEX8(0x00, key.e[0]);
    TEST_ASSERT_EQUAL_HEX8(0x01, key.e[1]);
    TEST_ASSERT_EQUAL_HEX8(0x00, key.e[2]);
    TEST_ASSERT_EQUAL_HEX8(0x01, key.e[3]);
}

void test_jwks_find_missing_kid_fails()
{
    pc_oidc_key key;
    key.loaded = PROTO_FALSE;
    TEST_ASSERT_FALSE(pc_oidc_jwks_find(K_JWKS, "nope", &key));
}

void test_verify_valid_token_and_claims()
{
    pc_oidc_claims c;
    pc_oidc_result rc = pc_oidc_verify(K_TOK_VALID, strlen(K_TOK_VALID), K_JWKS, ISS, AUD, NOW, &c);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_OK, rc);
    TEST_ASSERT_EQUAL_STRING("user-42", c.sub);
    TEST_ASSERT_EQUAL_STRING("alice@example.com", c.email);
    TEST_ASSERT_TRUE(c.iat == 1700000000LL);
    TEST_ASSERT_TRUE(c.exp == 4102444800LL); // > 2^31: requires 64-bit claims
}

void test_verify_aud_array()
{
    pc_oidc_result rc = pc_oidc_verify(K_TOK_AUDARR, strlen(K_TOK_AUDARR), K_JWKS, ISS, AUD, NOW, NULL);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_OK, rc); // "client-123" is one element of the aud array
}

void test_reject_expired()
{
    pc_oidc_result rc = pc_oidc_verify(K_TOK_EXPIRED, strlen(K_TOK_EXPIRED), K_JWKS, ISS, AUD, NOW, NULL);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_EXPIRED, rc);
}

void test_reject_wrong_issuer()
{
    pc_oidc_result rc =
        pc_oidc_verify(K_TOK_VALID, strlen(K_TOK_VALID), K_JWKS, "https://evil.example", AUD, NOW, NULL);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_ISS, rc);
}

void test_reject_wrong_audience()
{
    pc_oidc_result rc = pc_oidc_verify(K_TOK_VALID, strlen(K_TOK_VALID), K_JWKS, ISS, "other-client", NOW, NULL);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_AUD, rc);
}

void test_reject_non_rs256_header()
{
    pc_oidc_result rc = pc_oidc_verify(K_TOK_HS256HDR, strlen(K_TOK_HS256HDR), K_JWKS, ISS, AUD, NOW, NULL);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_ALG, rc);
}

void test_reject_tampered_payload()
{
    char tok[1024];
    strcpy(tok, K_TOK_VALID);
    char *dot = strchr(tok, '.'); // end of header
    char *c = dot + 6;            // a byte inside the payload segment
    *c = (*c == 'A') ? 'B' : 'A'; // flip to a different valid base64url char
    pc_oidc_result rc = pc_oidc_verify(tok, strlen(tok), K_JWKS, ISS, AUD, NOW, NULL);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_SIGNATURE, rc);
}

void test_reject_tampered_signature()
{
    char tok[1024];
    strcpy(tok, K_TOK_VALID);
    char *sig = strrchr(tok, '.') + 1; // first char of the signature segment
    *sig = (*sig == 'Q') ? 'R' : 'Q';  // flip a meaningful (non-padding) base64url char
    pc_oidc_result rc = pc_oidc_verify(tok, strlen(tok), K_JWKS, ISS, AUD, NOW, NULL);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_SIGNATURE, rc);
}

void test_reject_unknown_key()
{
    // JWKS whose only key has a different kid than the token's.
    const char *other = "{\"keys\":[{\"kty\":\"RSA\",\"kid\":\"different\",\"n\":\"AQAB\",\"e\":\"AQAB\"}]}";
    pc_oidc_result rc = pc_oidc_verify(K_TOK_VALID, strlen(K_TOK_VALID), other, ISS, AUD, NOW, NULL);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_KEY, rc);
}

void test_reject_malformed()
{
    // No kid extractable -> the sole JWKS key is selected, then the token shape
    // fails to split into three segments.
    pc_oidc_result rc = pc_oidc_verify("not-a-jwt", 9, K_JWKS, ISS, AUD, NOW, NULL);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT, rc);
}

// token_kid rejects null args, a zero-cap output and a header segment that does not
// base64url-decode.
void test_token_kid_guards()
{
    char kid[64];
    TEST_ASSERT_FALSE(pc_oidc_token_kid(NULL, 10, kid, sizeof(kid)));
    TEST_ASSERT_FALSE(pc_oidc_token_kid("a.b.c", 5, NULL, sizeof(kid)));
    TEST_ASSERT_FALSE(pc_oidc_token_kid("a.b.c", 5, kid, 0));
    TEST_ASSERT_FALSE(pc_oidc_token_kid("A.payload.sig", 13, kid, sizeof(kid))); // 1-char header
}

// jwks_find rejects null args, a document with no keys array, an unterminated key
// object, and a key whose kid matches but is unusable (no modulus).
void test_jwks_find_guards()
{
    pc_oidc_key key;
    key.loaded = PROTO_FALSE;
    TEST_ASSERT_FALSE(pc_oidc_jwks_find(NULL, "k", &key));
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"keys\":[]}", "k", NULL));
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"foo\":1}", "k", &key));                    // no keys array
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"keys\":[{\"kid\":\"x\"", "x", &key));      // unterminated object
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"keys\":[{\"kid\":\"k1\"}]}", "k1", &key)); // kid matches, no n/e
}

// verify_with_key rejects a null / unloaded key, a zero length, and a header that does
// not decode; verify() rejects tokens with the wrong number of segments and a
// wrong-length signature.
void test_verify_guards_and_malformed()
{
    pc_oidc_key unloaded;
    unloaded.loaded = PROTO_FALSE;
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT, pc_oidc_verify_with_key("a.b.c", 5, &unloaded, ISS, AUD, NOW, NULL));

    pc_oidc_key key;
    key.loaded = PROTO_FALSE;
    TEST_ASSERT_TRUE(pc_oidc_jwks_find(K_JWKS, "test-key-1", &key));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT, pc_oidc_verify_with_key(NULL, 5, &key, ISS, AUD, NOW, NULL));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT, pc_oidc_verify_with_key("a.b.c", 0, &key, ISS, AUD, NOW, NULL));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT,
                          pc_oidc_verify_with_key("A.b.c", 5, &key, ISS, AUD, NOW, NULL)); // header decode fail

    // Wrong segment counts (one '.' / three '.').
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT, pc_oidc_verify("aa.bb", 5, K_JWKS, ISS, AUD, NOW, NULL));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT, pc_oidc_verify("a.b.c.d", 7, K_JWKS, ISS, AUD, NOW, NULL));

    // A valid header/payload but a truncated (wrong-length) signature.
    char buf[2048];
    snprintf(buf, sizeof(buf), "%s", K_TOK_VALID);
    char *last_dot = strrchr(buf, '.');
    last_dot[6] = '\0'; // keep only 5 signature chars -> decodes to != 256 bytes
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT, pc_oidc_verify(buf, strlen(buf), K_JWKS, ISS, AUD, NOW, NULL));
}

// Crafted JWKS documents exercise the JSON field scanner and the RSA-JWK loader:
// an empty document, an escaped/over-long/unterminated/non-string kid, a key missing
// its exponent, and exponents that do or do not fit the 4-byte field.
void test_jwks_malformed_keys()
{
    pc_oidc_key key;
    key.loaded = PROTO_FALSE;

    TEST_ASSERT_FALSE(pc_oidc_jwks_find("", "k", &key)); // needle longer than the document

    // escaped char inside a string value + a mismatching kid (get_str runs, then rejects).
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"keys\":[{\"kid\":\"a\\\\b\"}]}", "zzz", &key));
    // kid string with no closing quote.
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"keys\":[{\"kid\":\"abc}]}", "abc", &key));
    // kid value is not a string.
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"keys\":[{\"kid\":true}]}", "x", &key));

    // a kid longer than the kid buffer (get_str overflow); the key itself is usable.
    char jwks[400];
    int p = snprintf(jwks, sizeof(jwks), "{\"keys\":[{\"kid\":\"");
    for (int i = 0; i < 200; i++)
    {
        jwks[p++] = 'a';
    }
    snprintf(jwks + p, sizeof(jwks) - p, "\",\"n\":\"AAAA\",\"e\":\"AQAB\"}]}");
    TEST_ASSERT_TRUE(pc_oidc_jwks_find(jwks, NULL, &key));

    // a key with a modulus but no exponent.
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"keys\":[{\"n\":\"AAAA\"}]}", NULL, &key));
    // an exponent too wide for the 4-byte field.
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"keys\":[{\"n\":\"AAAA\",\"e\":\"AAAAAAAA\"}]}", NULL, &key));
    // an exponent of 5 bytes with a leading zero, which is stripped and accepted.
    TEST_ASSERT_TRUE(pc_oidc_jwks_find("{\"keys\":[{\"n\":\"AAAA\",\"e\":\"AAAAAAA\"}]}", NULL, &key));
}

// Provision the baseline host key into NVS, the way a board's is, and mirror it into @p key so a
// test can mint a validly-signed token and verify it. Idempotent - each token-minting test calls it
// rather than depending on an earlier test having run.
static void setup_rt_key(pc_oidc_key *key)
{
    TEST_ASSERT_TRUE(pc_nvs_put_blob(PC_SSH_HOST_KEY_NS, PC_SSH_HOST_KEY_ITEM, PC_SSH_BASELINE_KEY_DER,
                                     PC_SSH_BASELINE_KEY_DER_LEN));
    TEST_ASSERT_EQUAL_INT(0, pc_ssh_rsa_load_pubkey());
    key->loaded = PROTO_TRUE;
    memcpy(key->n, PC_SSH_BASELINE_KEY_N, 256);
    memcpy(key->e, PC_SSH_BASELINE_KEY_E, 4);
}

// Wrap @p hdr_json as the header segment of an otherwise-dummy 3-segment token, so
// pc_oidc_token_kid() runs the JSON field scanner over exactly those bytes (the decoded
// header is the scanner's whole buffer, letting a value sit flush against its end).
static void kid_token_from_header(const char *hdr_json, char *tok, size_t cap)
{
    char seg0[256];
    b64url_enc((const uint8_t *)hdr_json, strlen(hdr_json), seg0);
    snprintf(tok, cap, "%s.payload.signature", seg0);
}

// find_field's separator skip accepts every JSON whitespace form between the member name
// and its value, and stops cleanly when the value is missing entirely (buffer ends first).
void test_find_field_separator_forms()
{
    char tok[512];
    char kid[64];

    // space / tab / colon / newline / CR all skipped before the value.
    kid_token_from_header("{\"kid\" \t:\n\r \"a\"}", tok, sizeof(tok));
    TEST_ASSERT_TRUE(pc_oidc_token_kid(tok, strlen(tok), kid, sizeof(kid)));
    TEST_ASSERT_EQUAL_STRING("a", kid);

    // The member name is the last thing in the buffer: the skip loop runs off the end.
    kid_token_from_header("{\"kid\": ", tok, sizeof(tok));
    TEST_ASSERT_FALSE(pc_oidc_token_kid(tok, strlen(tok), kid, sizeof(kid)));
}

// find_field's value scanners stop at the buffer end rather than reading past it: a string
// whose final byte is a lone backslash, and a number that runs to the last byte.
void test_find_field_value_runs_to_buffer_end()
{
    char tok[512];
    char kid[64];

    // Trailing backslash with no following byte: the escape skip must not step past the end.
    kid_token_from_header("{\"kid\":\"ab\\", tok, sizeof(tok));
    TEST_ASSERT_FALSE(pc_oidc_token_kid(tok, strlen(tok), kid, sizeof(kid)));

    // Digits run to the final byte; the value is a number, so get_str rejects it.
    kid_token_from_header("{\"kid\":123", tok, sizeof(tok));
    TEST_ASSERT_FALSE(pc_oidc_token_kid(tok, strlen(tok), kid, sizeof(kid)));

    // A value that is neither string, array, '-' nor a digit is rejected outright.
    kid_token_from_header("{\"kid\":!}", tok, sizeof(tok));
    TEST_ASSERT_FALSE(pc_oidc_token_kid(tok, strlen(tok), kid, sizeof(kid)));
}

// A negative numeric claim is parsed with its sign, and a non-numeric `exp` is rejected.
void test_get_int64_negative_and_non_numeric()
{
    pc_oidc_key key;
    setup_rt_key(&key);
    char tok[2048];
    char pl[256];

    // exp = -5 exercises the signed path; any now_unix is >= -5, so the token reads as expired.
    snprintf(pl, sizeof(pl), "{\"iss\":\"%s\",\"aud\":\"%s\",\"exp\":-5}", ISS, AUD);
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_EXPIRED, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));

    // exp present but a string, not a number -> get_int64 rejects on type.
    snprintf(pl, sizeof(pl), "{\"iss\":\"%s\",\"aud\":\"%s\",\"exp\":\"4102444800\"}", ISS, AUD);
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_EXPIRED, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));
}

// aud matching compares the whole value: a same-length-but-different string, a same-length
// -but-different array entry, and a numeric aud are all rejected.
void test_aud_same_length_mismatch_and_numeric()
{
    pc_oidc_key key;
    setup_rt_key(&key);
    char tok[2048];
    char pl[256];

    // "client-124" is exactly as long as the expected "client-123" but differs.
    snprintf(pl, sizeof(pl), "{\"iss\":\"%s\",\"aud\":\"client-124\",\"exp\":4102444800}", ISS);
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_AUD, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));

    // Same, inside an array: the entry length matches so memcmp decides.
    snprintf(pl, sizeof(pl), "{\"iss\":\"%s\",\"aud\":[\"client-124\"],\"exp\":4102444800}", ISS);
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_AUD, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));

    // aud is a number: neither the string nor the array form applies.
    snprintf(pl, sizeof(pl), "{\"iss\":\"%s\",\"aud\":123,\"exp\":4102444800}", ISS);
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_AUD, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));
}

// split3 requires all three segments to be non-empty, whichever one is missing.
void test_split3_rejects_empty_segments()
{
    pc_oidc_key key;
    key.loaded = PROTO_FALSE;
    TEST_ASSERT_TRUE(pc_oidc_jwks_find(K_JWKS, "test-key-1", &key));

    const char *empty_hdr = ".b.c";
    const char *empty_pl = "a..c";
    const char *empty_sig = "a.b.";
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT,
                          pc_oidc_verify_with_key(empty_hdr, strlen(empty_hdr), &key, ISS, AUD, NOW, NULL));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT,
                          pc_oidc_verify_with_key(empty_pl, strlen(empty_pl), &key, ISS, AUD, NOW, NULL));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT,
                          pc_oidc_verify_with_key(empty_sig, strlen(empty_sig), &key, ISS, AUD, NOW, NULL));
}

// right_align only tolerates an over-long field when the extra byte is a leading zero, and
// an empty exponent is rejected outright.
void test_jwk_field_widths()
{
    pc_oidc_key key;
    key.loaded = PROTO_FALSE;

    // e decodes to 5 bytes whose leading byte is NOT zero -> does not fit the 4-byte field.
    const uint8_t e5[5] = {0x01, 0x00, 0x00, 0x00, 0x01};
    char e_b64[16];
    b64url_enc(e5, sizeof(e5), e_b64);
    char jwks[128];
    snprintf(jwks, sizeof(jwks), "{\"keys\":[{\"n\":\"AAAA\",\"e\":\"%s\"}]}", e_b64);
    TEST_ASSERT_FALSE(pc_oidc_jwks_find(jwks, NULL, &key));

    // An empty exponent decodes to zero bytes.
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"keys\":[{\"n\":\"AAAA\",\"e\":\"\"}]}", NULL, &key));

    // n decodes to 258 bytes - over the 256-byte modulus field by more than one leading zero.
    uint8_t n_big[258];
    for (size_t i = 0; i < sizeof(n_big); i++)
    {
        n_big[i] = (uint8_t)(i + 1);
    }
    char n_b64[400];
    b64url_enc(n_big, sizeof(n_big), n_b64);
    char jwks_bign[600];
    snprintf(jwks_bign, sizeof(jwks_bign), "{\"keys\":[{\"n\":\"%s\",\"e\":\"AQAB\"}]}", n_b64);
    TEST_ASSERT_FALSE(pc_oidc_jwks_find(jwks_bign, NULL, &key));
}

// jwks_find with an empty (rather than null) kid means "any usable key", and the scan ends
// when the document runs out mid-array instead of reading past it.
void test_jwks_empty_kid_and_truncated_document()
{
    pc_oidc_key key;
    key.loaded = PROTO_FALSE;

    // Empty kid behaves like "no kid requested": the first usable RSA key is taken.
    TEST_ASSERT_TRUE(pc_oidc_jwks_find(K_JWKS, "", &key));
    TEST_ASSERT_TRUE(key.loaded);

    // Empty kid + an unusable key: the scan must not treat it as a kid match and stop early,
    // it just moves on and runs out of document.
    pc_oidc_key none;
    none.loaded = PROTO_FALSE;
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"keys\":[{\"kid\":\"k1\"}]}", "", &none));

    // The document ends exactly at the key object's closing brace: the scan loop terminates
    // on the buffer bound rather than on a failed memchr.
    TEST_ASSERT_FALSE(pc_oidc_jwks_find("{\"keys\":[{\"kid\":\"a\"}", "zzz", &none));
}

// verify_with_key's argument guards: a null key pointer and a token over the length cap.
void test_verify_with_key_arg_guards()
{
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT, pc_oidc_verify_with_key("a.b.c", 5, NULL, ISS, AUD, NOW, NULL));

    pc_oidc_key key;
    key.loaded = PROTO_FALSE;
    TEST_ASSERT_TRUE(pc_oidc_jwks_find(K_JWKS, "test-key-1", &key));

    // Longer than PC_OIDC_MAX_LEN: rejected before any parsing happens.
    char big[PC_OIDC_MAX_LEN + 101];
    memset(big, 'a', sizeof(big) - 1);
    big[sizeof(big) - 1] = '\0';
    big[10] = '.';
    big[20] = '.';
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT, pc_oidc_verify_with_key(big, strlen(big), &key, ISS, AUD, NOW, NULL));
}

// The iss / aud checks are opt-in: null or empty expectations skip them, while a set
// expectation against a token that has no iss claim at all still fails closed.
void test_verify_optional_iss_aud_expectations()
{
    pc_oidc_key key;
    setup_rt_key(&key);
    char tok[2048];
    char pl[256];

    // A token carrying neither iss nor aud verifies when neither is expected...
    snprintf(pl, sizeof(pl), "{\"sub\":\"u\",\"exp\":4102444800}");
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_OK, pc_oidc_verify_with_key(tok, strlen(tok), &key, NULL, NULL, NOW, NULL));
    // ...and equally when the expectations are present but empty.
    TEST_ASSERT_EQUAL_INT(PC_OIDC_OK, pc_oidc_verify_with_key(tok, strlen(tok), &key, "", "", NOW, NULL));

    // But an expected issuer against a token with no iss claim is a mismatch.
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_ISS, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, NULL, NOW, NULL));
}

// exp is mandatory; nbf is optional and passes once it is in the past.
void test_verify_exp_required_nbf_past()
{
    pc_oidc_key key;
    setup_rt_key(&key);
    char tok[2048];
    char pl[256];

    // No exp claim at all -> treated as expired, not as "no expiry".
    snprintf(pl, sizeof(pl), "{\"iss\":\"%s\",\"aud\":\"%s\",\"sub\":\"u\"}", ISS, AUD);
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_EXPIRED, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));

    // nbf already passed -> accepted.
    snprintf(pl, sizeof(pl), "{\"iss\":\"%s\",\"aud\":\"%s\",\"exp\":4102444800,\"nbf\":1600000000}", ISS, AUD);
    make_jwt(pl, tok, sizeof(tok));
    TEST_ASSERT_EQUAL_INT(PC_OIDC_OK, pc_oidc_verify_with_key(tok, strlen(tok), &key, ISS, AUD, NOW, NULL));
}

// Leave exactly @p keep bytes free in the scratch arena, so the next N borrows can be made
// to succeed or fail individually.
static void scratch_leave(size_t keep)
{
    pc_plaintext_reset();
    size_t cap = pc_plaintext_capacity();
    TEST_ASSERT_TRUE(cap > keep);
    TEST_ASSERT_NOT_NULL(pc_plaintext_alloc(cap - keep, 1));
}

// verify_with_key borrows four buffers from the scratch arena and must fail closed if ANY of
// them cannot be had - not just the first. Starve each borrow in turn.
void test_verify_scratch_partial_exhaustion()
{
    pc_oidc_key key;
    key.loaded = PROTO_FALSE;
    TEST_ASSERT_TRUE(pc_oidc_jwks_find(K_JWKS, "test-key-1", &key));

    const size_t HDR = 512;
    const size_t SIG = PC_OIDC_RSA_BYTES;
    const size_t PL = PC_OIDC_MAX_LEN;
    const size_t ISSC = 256;

    // Room for the header buffer but not the signature buffer.
    scratch_leave(HDR + SIG - 1);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT,
                          pc_oidc_verify_with_key(K_TOK_VALID, strlen(K_TOK_VALID), &key, ISS, AUD, NOW, NULL));

    // Room for header + signature but not the payload buffer.
    scratch_leave(HDR + SIG + PL - 1);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT,
                          pc_oidc_verify_with_key(K_TOK_VALID, strlen(K_TOK_VALID), &key, ISS, AUD, NOW, NULL));

    // Room for everything except the issuer buffer.
    scratch_leave(HDR + SIG + PL + ISSC - 1);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_ERR_FORMAT,
                          pc_oidc_verify_with_key(K_TOK_VALID, strlen(K_TOK_VALID), &key, ISS, AUD, NOW, NULL));

    // With room for all four the same token verifies, proving the arena was the only thing
    // failing above.
    scratch_leave(HDR + SIG + PL + ISSC);
    TEST_ASSERT_EQUAL_INT(PC_OIDC_OK,
                          pc_oidc_verify_with_key(K_TOK_VALID, strlen(K_TOK_VALID), &key, ISS, AUD, NOW, NULL));
    pc_plaintext_reset();
}

// --- pc_bignum.cpp direct coverage --------------------------------------------------
//
// Group-14 DH (bn_expmod_group14 / bn_dh_validate) is never reached through the OIDC
// verifier - RSA verification uses its own full-width bignum path in ssh_rsa.cpp, not
// the Montgomery group-14 machinery. These call the public bn_* API directly.

// bn_is_zero: the all-zero case runs the limb loop to completion; a nonzero limb returns
// early instead.
void test_bn_is_zero(void)
{
    pc_bignum z;
    memset(z.d, 0, sizeof(z.d));
    TEST_ASSERT_TRUE(bn_is_zero(&z));

    pc_bignum nz;
    memset(nz.d, 0, sizeof(nz.d));
    nz.d[0] = 1;
    TEST_ASSERT_FALSE(bn_is_zero(&nz));
}

// bn_dh_validate (RFC 4253 §8: 1 < v < p-1) exercises both the "must be > 1" scan (the
// short-circuit when no high limb is set, and the early-break when one is) and the
// "must be < p-1" comparison (less / equal / greater, via bn_cmp/bn_cmp_raw).
void test_bn_dh_validate_range_guards(void)
{
    pc_bignum v;

    // v == 0: no high limb set, d[0] <= 1 -> reject.
    memset(v.d, 0, sizeof(v.d));
    TEST_ASSERT_EQUAL_INT(-1, bn_dh_validate(&v));

    // v == 1: same short path, still <= 1 -> reject.
    v.d[0] = 1;
    TEST_ASSERT_EQUAL_INT(-1, bn_dh_validate(&v));

    // v == 2: short path, but d[0] > 1 clears the ">1" guard; well under p-1 -> accept.
    v.d[0] = 2;
    TEST_ASSERT_EQUAL_INT(0, bn_dh_validate(&v));

    // v == p: a high limb is set (the ">1" scan finds it and breaks early), but v > p-1
    // -> reject via the bn_cmp "greater than" branch.
    v = group14_p;
    TEST_ASSERT_EQUAL_INT(-1, bn_dh_validate(&v));

    // v == p-1: high limb set, but v is not < p-1 (equal) -> reject.
    v = group14_p;
    v.d[0]--;
    TEST_ASSERT_EQUAL_INT(-1, bn_dh_validate(&v));

    // v == p-2: high limb set, and v < p-1 -> accept.
    v = group14_p;
    v.d[0] -= 2;
    TEST_ASSERT_EQUAL_INT(0, bn_dh_validate(&v));
}

// bn_expmod_group14: the native software Montgomery path (bn_init/bn_monpro/bn_shl1/
// bn_sub_inplace) is otherwise completely unreached from the OIDC tests. Since
// 2^5 = 32 is far smaller than the group-14 prime, the expected result needs no
// independent modexp implementation to check against - it is exactly base^exp with no
// modular reduction - while the 2048-iteration square-and-multiply loop underneath still
// runs in full, exercising bn_init's one-time R/R^2 setup and every bn_monpro reduction
// branch along the way.
void test_bn_expmod_group14_small_exponent(void)
{
    pc_bignum exp;
    memset(exp.d, 0, sizeof(exp.d));
    exp.d[0] = 5;

    pc_bignum out;
    bn_expmod_group14(&out, &group14_g, &exp);

    pc_bignum expected;
    memset(expected.d, 0, sizeof(expected.d));
    expected.d[0] = 32; // 2^5, unreduced since 32 << group14_p
    TEST_ASSERT_EQUAL_INT(0, bn_cmp(&out, &expected));
}

// bn_init() memoizes the Montgomery R/R^2 setup behind a static "already initialized"
// guard (s_g14.initialized) so it only runs once for the whole process; the test above is
// what performs that first-time setup. This second, independent modexp call runs after it
// (same process, RUN_TEST order) and is what exercises the early-return guard itself -
// s_g14.initialized is already true, so bn_init() must return immediately without
// recomputing R/R^2.
void test_bn_expmod_group14_reinit_short_circuit(void)
{
    pc_bignum exp;
    memset(exp.d, 0, sizeof(exp.d));
    exp.d[0] = 3;

    pc_bignum out;
    bn_expmod_group14(&out, &group14_g, &exp);

    pc_bignum expected;
    memset(expected.d, 0, sizeof(expected.d));
    expected.d[0] = 8; // 2^3, unreduced since 8 << group14_p
    TEST_ASSERT_EQUAL_INT(0, bn_cmp(&out, &expected));
}

// bn_monpro's Montgomery-domain product can land >= p after the SOS reduction pass and
// needs the conditional correction subtract (bn_sub_inplace) - never exercised by the small
// base/exponent above, since the running Montgomery product never grows past p there. base =
// exp = 255 (0xFF, 8 bits) is nowhere near p, but 255's 8 set bits mean several genuine
// multiply-ins during the square-and-multiply loop, which is enough for the running product
// to cross p at a couple of points along the way - found by exhaustively probing base bit
// widths for the smallest one that reaches this branch at all. The expected value is
// 255^255 mod p, computed independently out-of-band (Python's arbitrary-precision pow(255,
// 255, p)) and pinned here as a constant, so this checks exact numeric correctness, not just
// that the code runs.
void test_bn_expmod_group14_large_operand_needs_reduction(void)
{
    static const char EXP255_255_MOD_P[] = "005e5c8b0eb95ab08f9d37ef127fc01bd0e33de52647528396d78d5f8da31989"
                                           "e67814f6bba1fb0f0207010ff5f2347b19d5f6598fc91bf5a88f77daa3d7b382"
                                           "fec484f3d205c06a34445384c0e7ab0d883788c68c012cb433055edda746a484"
                                           "09444ea91147273b79fc3eabb70eca552af650c234bb01ed404427f17cdddd71"
                                           "d08e39ef9c3982e3ce44e670456aa8154c1fdbd9c35947f494636a425c69bf89"
                                           "e9c75ad3b7a0a559af0f5da9947c8deba64417310713b23e7ef4de50bb2a3e90"
                                           "bc2ac3da5201cca8d6e5dfea887c4f7a4e92175d9f88bd2779b57f9eb35be752"
                                           "8f965a06da0ac41dcb3a34f1d8ab7d8fee620a94faa42c395997756b007ffeff";

    pc_bignum base;
    memset(base.d, 0, sizeof(base.d));
    base.d[0] = 255;

    pc_bignum exp;
    memset(exp.d, 0, sizeof(exp.d));
    exp.d[0] = 255;

    pc_bignum out;
    bn_expmod_group14(&out, &base, &exp);

    uint8_t expected_bytes[256];
    hex2bytes(expected_bytes, EXP255_255_MOD_P, 256);
    pc_bignum expected;
    bn_from_bytes(&expected, expected_bytes, 256);
    TEST_ASSERT_EQUAL_INT(0, bn_cmp(&out, &expected));
}

// --- ssh_rsa.cpp direct coverage -----------------------------------------------------

// SHA-512 selects the SHA-512 DigestInfo/hash in rsa_digest(), on both the sign and
// verify paths; RS256 (used by every OIDC token test above) is fixed to SHA-256, so
// SHA-512 is otherwise never reached.
void test_rsa_sign_verify_sha512(void)
{
    pc_oidc_key key;
    setup_rt_key(&key);

    static const char msg[] = "sha512 coverage message";
    uint8_t sig[PC_RSA_SIG_BYTES];
    TEST_ASSERT_EQUAL_INT(0, ssh_rsa_sign(tw, (const uint8_t *)msg, strlen(msg), PC_RSA_HASH_SHA512, sig));

    TEST_ASSERT_EQUAL_INT(0, pc_rsa_verify(PC_SSH_BASELINE_KEY_N, PC_SSH_BASELINE_KEY_E, tw, (const uint8_t *)msg,
                                           strlen(msg), sig, PC_RSA_SIG_BYTES, PC_RSA_HASH_SHA512));
}

// bn_modexp_full's private-exponent scan short-circuits to "result = 1" when every limb
// of the exponent is zero (top_limb never finds a set bit) - unreachable with any real
// RSA private key, but directly reachable through the native test fixture.
void test_rsa_sign_zero_exponent(void)
{
    // No real key has d == 0, so this goes to the primitive, which takes n and d directly.
    uint8_t n_be[PC_RSA_KEY_BYTES];
    uint8_t d_be[PC_RSA_KEY_BYTES];
    hex2bytes(n_be, RT_N, 256);
    memset(d_be, 0, sizeof(d_be));

    static const char msg[] = "zero exponent";
    uint8_t sig[PC_RSA_SIG_BYTES];
    TEST_ASSERT_EQUAL_INT(0,
                          pc_rsa_sign_sw(n_be, d_be, tw, (const uint8_t *)msg, strlen(msg), PC_RSA_HASH_SHA256, sig));

    // s = em^0 mod n == 1, encoded big-endian as 255 zero bytes followed by 0x01.
    for (size_t i = 0; i < PC_RSA_SIG_BYTES - 1; i++)
    {
        TEST_ASSERT_EQUAL_HEX8(0x00, sig[i]);
    }
    TEST_ASSERT_EQUAL_HEX8(0x01, sig[PC_RSA_SIG_BYTES - 1]);
}

// bn_reduce_full's "is r >= m" limb scan assumes greater-or-equal and looks MSB-down for
// the first differing limb to disprove it. With any real 2048-bit RSA modulus the operands
// differ within the first limb or two, so the scan never runs past a handful of high limbs
// and never finds every limb equal. A deliberately tiny modulus (n = 5, not a realistic RSA
// key - a focused unit test of the reduction's comparison loop, driven through pc_rsa_sign_sw
// with a value large enough to need many reduction steps)
// forces the scan to compare against 63 leading zero limbs on every one of the reduction's
// ~2048 steps (equal every time - the r[k] == m[k] continuation), and the long run of 0xFF
// pad bytes in the PKCS#1 block means the running remainder lands on exactly n itself at
// some steps too, so the scan also completes with no differing limb found at all.
void test_rsa_sign_tiny_modulus_reduction_equal_limbs(void)
{
    uint8_t n_be[PC_RSA_KEY_BYTES];
    uint8_t d_be[PC_RSA_KEY_BYTES];
    memset(n_be, 0, sizeof(n_be));
    n_be[PC_RSA_KEY_BYTES - 1] = 5; // n = 5
    memset(d_be, 0, sizeof(d_be));
    d_be[PC_RSA_KEY_BYTES - 1] = 1; // d = 1

    static const char msg[] = "tiny modulus";
    uint8_t sig[PC_RSA_SIG_BYTES];
    TEST_ASSERT_EQUAL_INT(0,
                          pc_rsa_sign_sw(n_be, d_be, tw, (const uint8_t *)msg, strlen(msg), PC_RSA_HASH_SHA256, sig));

    // Every result is < n == 5, so the high 255 bytes are all zero.
    for (size_t i = 0; i < PC_RSA_SIG_BYTES - 1; i++)
    {
        TEST_ASSERT_EQUAL_HEX8(0x00, sig[i]);
    }
    TEST_ASSERT_TRUE(sig[PC_RSA_SIG_BYTES - 1] < 5);
}

// pc_rsa_verify rejects a signature of the wrong length before touching any bignum
// state, and separately rejects (without crashing) a signature that is numerically >= the
// modulus (RFC 8017 requires s < n); an all-0xFF byte string is guaranteed larger than any
// 2048-bit RSA modulus whose top byte's MSB is clear, as RT_N's is.
void test_rsa_verify_length_and_range_guards(void)
{
    uint8_t n_be[PC_RSA_KEY_BYTES];
    hex2bytes(n_be, RT_N, 256);
    uint8_t e_be[4] = {0, 1, 0, 1};
    static const char msg[] = "guard check";

    uint8_t short_sig[10] = {0};
    TEST_ASSERT_EQUAL_INT(-1, pc_rsa_verify(n_be, e_be, tw, (const uint8_t *)msg, strlen(msg), short_sig,
                                            sizeof(short_sig), PC_RSA_HASH_SHA256));

    uint8_t big_sig[PC_RSA_KEY_BYTES];
    memset(big_sig, 0xFF, sizeof(big_sig));
    TEST_ASSERT_EQUAL_INT(-1, pc_rsa_verify(n_be, e_be, tw, (const uint8_t *)msg, strlen(msg), big_sig, sizeof(big_sig),
                                            PC_RSA_HASH_SHA256));
}

// bn_modexp_pub's public-exponent bit scan starts unconditionally at bit 31 with no
// precondition that e is nonzero (unlike bn_modexp_full's private-exponent scan, which is
// guarded by an earlier all-limbs-zero check covered by test_rsa_sign_zero_exponent above).
// A real "ssh-rsa" public exponent is never 0, but e's raw bytes come straight off the wire
// in pc_rsa_verify, so a malformed/zero e must not run past the top of the scan. e = 0
// drives `top` down to -1 (never finding a set bit), which is what this covers.
void test_rsa_verify_zero_public_exponent(void)
{
    uint8_t n_be[PC_RSA_KEY_BYTES];
    hex2bytes(n_be, RT_N, 256);
    uint8_t e_be[4] = {0, 0, 0, 0}; // e == 0
    static const char msg[] = "zero e";

    uint8_t sig[PC_RSA_SIG_BYTES] = {0};
    sig[PC_RSA_SIG_BYTES - 1] = 1; // s = 1, s < n so the range guard passes

    // s^0 mod n == 1, which never matches the expected PKCS#1 block, so verify still
    // fails - but only after bn_modexp_pub's e == 0 short-circuit runs without looping.
    TEST_ASSERT_EQUAL_INT(-1, pc_rsa_verify(n_be, e_be, tw, (const uint8_t *)msg, strlen(msg), sig, PC_RSA_SIG_BYTES,
                                            PC_RSA_HASH_SHA256));
}

// ssh_rsa_encode_pubkey: the not-yet-loaded guard, the too-small-buffer guard, and the
// success path - which exercises put_mpint's leading-zero-strip and MSB-pad logic in both
// directions in a single call. RT's e (00 01 00 01) has a leading zero to strip and its
// trimmed top byte's MSB is clear, so no pad byte is added; RT_N has no leading zero but
// its top byte's MSB is set, so a 0x00 pad byte is inserted ahead of it.
void test_rsa_encode_pubkey(void)
{
    // Not loaded -> guard (line coverage only; state is fully re-established below).
    ssh_host_pubkey.loaded = PROTO_FALSE;
    uint8_t out[SSH_RSA_PUBKEY_BLOB_MAX];
    size_t out_len = 0;
    TEST_ASSERT_EQUAL_INT(-1, ssh_rsa_encode_pubkey(out, &out_len, sizeof(out)));

    // Load the baseline key so n/e are known.
    pc_oidc_key key;
    setup_rt_key(&key);

    // Buffer too small.
    TEST_ASSERT_EQUAL_INT(-1, ssh_rsa_encode_pubkey(out, &out_len, 4));

    // Success path.
    TEST_ASSERT_EQUAL_INT(0, ssh_rsa_encode_pubkey(out, &out_len, sizeof(out)));

    // uint32 len("ssh-rsa") + "ssh-rsa".
    TEST_ASSERT_EQUAL_HEX8(0, out[0]);
    TEST_ASSERT_EQUAL_HEX8(0, out[1]);
    TEST_ASSERT_EQUAL_HEX8(0, out[2]);
    TEST_ASSERT_EQUAL_HEX8(7, out[3]);
    TEST_ASSERT_EQUAL_MEMORY("ssh-rsa", out + 4, 7);

    // mpint e: leading 0x00 stripped, trimmed top byte 0x01 has its MSB clear -> no pad,
    // 3-byte length.
    size_t p = 4 + 7;
    TEST_ASSERT_EQUAL_HEX8(0, out[p + 0]);
    TEST_ASSERT_EQUAL_HEX8(0, out[p + 1]);
    TEST_ASSERT_EQUAL_HEX8(0, out[p + 2]);
    TEST_ASSERT_EQUAL_HEX8(3, out[p + 3]);
    TEST_ASSERT_EQUAL_HEX8(0x01, out[p + 4]);
    TEST_ASSERT_EQUAL_HEX8(0x00, out[p + 5]);
    TEST_ASSERT_EQUAL_HEX8(0x01, out[p + 6]);
    p += 4 + 3;

    // mpint n: an RSA modulus is a full 2048 bits, so its top byte's MSB is always set and a 0x00
    // pad byte precedes it, length 257.
    TEST_ASSERT_TRUE((PC_SSH_BASELINE_KEY_N[0] & 0x80u) != 0);
    TEST_ASSERT_EQUAL_HEX8(0, out[p + 0]);
    TEST_ASSERT_EQUAL_HEX8(0, out[p + 1]);
    TEST_ASSERT_EQUAL_HEX8(1, out[p + 2]);
    TEST_ASSERT_EQUAL_HEX8(1, out[p + 3]); // 257 = 0x00000101
    TEST_ASSERT_EQUAL_HEX8(0x00, out[p + 4]);
    TEST_ASSERT_EQUAL_HEX8(PC_SSH_BASELINE_KEY_N[0], out[p + 5]);
    p += 4 + 1 + 256;
    TEST_ASSERT_EQUAL_INT((int)p, (int)out_len);
}

// put_mpint's "strip leading zero bytes" scan can run all the way to the end of the input
// (off == data_len) when every byte is zero - never hit by RT's real e or n above. A zero
// public exponent hits it, and the consequent src_len == 0 branch in the need_pad check
// right after, via a genuine mpint edge case: RFC 4251 SS5 encodes the integer zero as a
// zero-length string, which is exactly what off running to data_len and src_len landing on
// 0 produces.
void test_rsa_encode_pubkey_zero_exponent(void)
{
    // No key carries e == 0, so it is written straight into the public struct the encoder reads.
    pc_oidc_key key;
    setup_rt_key(&key);
    memset(ssh_host_pubkey.e_bytes, 0, sizeof(ssh_host_pubkey.e_bytes));

    uint8_t out[SSH_RSA_PUBKEY_BLOB_MAX];
    size_t out_len = 0;
    TEST_ASSERT_EQUAL_INT(0, ssh_rsa_encode_pubkey(out, &out_len, sizeof(out)));

    // mpint e: zero-length string (RFC 4251 SS5's canonical zero encoding) - just the
    // 4-byte length prefix, no pad byte, no data.
    size_t p = 4 + 7;
    TEST_ASSERT_EQUAL_HEX8(0, out[p + 0]);
    TEST_ASSERT_EQUAL_HEX8(0, out[p + 1]);
    TEST_ASSERT_EQUAL_HEX8(0, out[p + 2]);
    TEST_ASSERT_EQUAL_HEX8(0, out[p + 3]); // length 0
    p += 4;

    // Restore e for any later test.
    setup_rt_key(&key);
}

int main()
{
    UNITY_BEGIN();
    RUN_TEST(test_verify_scratch_partial_exhaustion);
    RUN_TEST(test_find_field_separator_forms);
    RUN_TEST(test_find_field_value_runs_to_buffer_end);
    RUN_TEST(test_get_int64_negative_and_non_numeric);
    RUN_TEST(test_aud_same_length_mismatch_and_numeric);
    RUN_TEST(test_split3_rejects_empty_segments);
    RUN_TEST(test_jwk_field_widths);
    RUN_TEST(test_jwks_empty_kid_and_truncated_document);
    RUN_TEST(test_verify_with_key_arg_guards);
    RUN_TEST(test_verify_optional_iss_aud_expectations);
    RUN_TEST(test_verify_exp_required_nbf_past);
    RUN_TEST(test_oidc_parse_edge_guards);
    RUN_TEST(test_oidc_signed_claim_guards);
    RUN_TEST(test_jwks_malformed_keys);
    RUN_TEST(test_token_kid_guards);
    RUN_TEST(test_jwks_find_guards);
    RUN_TEST(test_verify_guards_and_malformed);
    RUN_TEST(test_token_kid);
    RUN_TEST(test_jwks_find);
    RUN_TEST(test_jwks_find_missing_kid_fails);
    RUN_TEST(test_verify_valid_token_and_claims);
    RUN_TEST(test_verify_aud_array);
    RUN_TEST(test_reject_expired);
    RUN_TEST(test_reject_wrong_issuer);
    RUN_TEST(test_reject_wrong_audience);
    RUN_TEST(test_reject_non_rs256_header);
    RUN_TEST(test_reject_tampered_payload);
    RUN_TEST(test_reject_tampered_signature);
    RUN_TEST(test_reject_unknown_key);
    RUN_TEST(test_reject_malformed);
    RUN_TEST(test_bn_is_zero);
    RUN_TEST(test_bn_dh_validate_range_guards);
    RUN_TEST(test_bn_expmod_group14_small_exponent);
    RUN_TEST(test_bn_expmod_group14_reinit_short_circuit);
    RUN_TEST(test_bn_expmod_group14_large_operand_needs_reduction);
    RUN_TEST(test_rsa_sign_verify_sha512);
    RUN_TEST(test_rsa_sign_zero_exponent);
    RUN_TEST(test_rsa_sign_tiny_modulus_reduction_equal_limbs);
    RUN_TEST(test_rsa_verify_length_and_range_guards);
    RUN_TEST(test_rsa_verify_zero_public_exponent);
    RUN_TEST(test_rsa_encode_pubkey);
    RUN_TEST(test_rsa_encode_pubkey_zero_exponent);
    return UNITY_END();
}
