#!/usr/bin/env python3
# Generate SSH c2s (client->server) compression golden vectors the way OpenSSH does:
# one zlib stream (windowBits=15 -> 32 KB window, context takeover) flushed per packet with
# Z_PARTIAL_FLUSH. Emits C arrays the ssh_inflate test decodes packet-by-packet.
import zlib

# Packet plaintexts, crafted to exercise:
#  - fixed-Huffman blocks (short/simple),
#  - dynamic-Huffman blocks (longer, skewed byte distribution),
#  - stored blocks (incompressible random-ish bytes),
#  - cross-packet back-references (later packets repeat earlier content -> matches into prior window).
packets = [
    b"GET / HTTP/1.1\r\nHost: device.local\r\n\r\n",
    b"the quick brown fox jumps over the lazy dog; " * 6,
    b"GET / HTTP/1.1\r\nHost: device.local\r\n\r\n",  # identical to packet 0 -> long back-ref into window
    bytes((i * 37 + 11) & 0xFF for i in range(400)),  # high-entropy -> likely stored/less compressible
    b"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" + (b"the quick brown fox " * 10),  # RLE-ish + repeat
    b"x",  # tiny single-byte packet
    b"",  # empty payload (SSH can send a 0-length compressed payload)
    b"final packet after an empty one, references the fox: the quick brown fox\n",
]

co = zlib.compressobj(6, zlib.DEFLATED, 15)  # level 6, DEFLATE, 32 KB window + zlib wrapper (as OpenSSH)
comp_packets = []
for p in packets:
    c = co.compress(p) + co.flush(zlib.Z_PARTIAL_FLUSH)  # exactly OpenSSH compress.c's per-packet flush
    comp_packets.append(c)


def c_array(name, data):
    if len(data) == 0:
        return f"static const uint8_t {name}[1] = {{0}}; // empty\n"
    body = ", ".join(str(b) for b in data)
    return f"static const uint8_t {name}[{len(data)}] = {{{body}}};\n"


out = []
out.append("// GENERATED by tools/crypto/gen_ssh_inflate_vectors.py - do not edit by hand.\n")
out.append("// zlib compressobj(6, DEFLATED, 15) + Z_PARTIAL_FLUSH per packet (OpenSSH's c2s format).\n")
out.append(f"#define SSH_INFLATE_NVEC {len(packets)}\n")
for i, (p, c) in enumerate(zip(packets, comp_packets)):
    out.append(c_array(f"vec_plain_{i}", p))
    out.append(c_array(f"vec_comp_{i}", c))
# tables of pointers + lengths
out.append("static const uint8_t *const vec_plain[SSH_INFLATE_NVEC] = {")
out.append(", ".join(f"vec_plain_{i}" for i in range(len(packets))) + "};\n")
out.append("static const size_t vec_plain_len[SSH_INFLATE_NVEC] = {")
out.append(", ".join(str(len(p)) for p in packets) + "};\n")
out.append("static const uint8_t *const vec_comp[SSH_INFLATE_NVEC] = {")
out.append(", ".join(f"vec_comp_{i}" for i in range(len(packets))) + "};\n")
out.append("static const size_t vec_comp_len[SSH_INFLATE_NVEC] = {")
out.append(", ".join(str(len(c)) for c in comp_packets) + "};\n")

import os

dest = os.path.join(
    os.path.dirname(__file__), "..", "test", "unit", "ssh", "test_ssh_inflate", "ssh_inflate_vectors.inc"
)
with open(dest, "w", newline="\n") as f:
    f.write("".join(out))
print("wrote", os.path.normpath(dest))
for i, (p, c) in enumerate(zip(packets, comp_packets)):
    print(f"  packet {i}: plain={len(p)} comp={len(c)}")
