#!/usr/bin/env python3
"""Generate a TLS 1.3 record-layer known-answer vector as C arrays for test_tls_record.

The C record layer is pinned byte for byte against an independent reconstruction: HKDF-Expand-Label
(RFC 8446 sec 7.1) from stdlib hmac/hashlib, and AEAD_AES_128_GCM from the cryptography package
(OpenSSL), neither of which shares code with ProtoCore. The same shape as the DTLS 1.3 vector in
test/unit/src/network_drivers/presentation/security/dtls/test_dtls_record/test_dtls_record.c, over the
TLS record header instead.

    python3 -m tools.crypto.gen_tls_record_kat

Run once and paste the result into the test; the C protect() must reproduce it byte for byte.
"""

import hashlib
import hmac

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

SECRET = bytes(range(32))
SEQ = 5
CONTENT_TYPE = 22  # handshake
PLAINTEXT = b"hello tls 1.3"

TAG_LEN = 16
LEGACY_VERSION = 0x0303
CT_APPLICATION_DATA = 23


def hkdf_expand(prk, info, length):
    out = b""
    t = b""
    counter = 1
    while len(out) < length:
        t = hmac.new(prk, t + info + bytes([counter]), hashlib.sha256).digest()
        out += t
        counter += 1
    return out[:length]


def expand_label(secret, label, context, length):
    full = b"tls13 " + label
    info = length.to_bytes(2, "big") + bytes([len(full)]) + full + bytes([len(context)]) + context
    return hkdf_expand(secret, info, length)


def emit_array(name, data):
    out = ["static const uint8_t %s[%d] = {" % (name, len(data))]
    for i in range(0, len(data), 12):
        out.append("    " + " ".join("0x%02x," % b for b in data[i : i + 12]))
    out.append("};")
    return "\n".join(out)


def main():
    key = expand_label(SECRET, b"key", b"", 16)
    iv = expand_label(SECRET, b"iv", b"", 12)

    nonce = bytearray(iv)
    for i in range(8):
        nonce[len(nonce) - 1 - i] ^= (SEQ >> (8 * i)) & 0xFF

    inner = PLAINTEXT + bytes([CONTENT_TYPE])
    header = bytes([CT_APPLICATION_DATA, LEGACY_VERSION >> 8, LEGACY_VERSION & 0xFF]) + (len(inner) + TAG_LEN).to_bytes(
        2, "big"
    )
    body = AESGCM(key).encrypt(bytes(nonce), inner, header)

    print("// Generated by tools/crypto/gen_tls_record_kat.py")
    print(emit_array("KAT_KEY", key))
    print(emit_array("KAT_IV", iv))
    print(emit_array("KAT_WIRE", header + body))
    print('static const char *KAT_PLAINTEXT = "%s";' % PLAINTEXT.decode())
    print("static const uint64_t KAT_SEQ = %d;" % SEQ)
    print("static const uint8_t KAT_CT = %d;" % CONTENT_TYPE)


if __name__ == "__main__":
    main()
