#!/usr/bin/env python3
# Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Emit the two RSA host keys the SSH and OIDC suites provision NVS with. The RSA half of the pairing
# test/support/baseline_keys.h and test/support/throwaway_key.h already make for Ed25519 - a fixed
# committed key for deterministic regression, and a fresh one per run so nothing passes by matching
# one key. RSA-2048 keygen is not something a test can do in C, so this runs at build time instead:
#
#   baseline   the committed fixture key (test/fixtures/ssh_test_host_key/ssh_test_host_key.h)
#   throwaway  a new RSA-2048 key on every run of test/run_tests.sh
#
# A failing run's throwaway key stays on disk in the output below, and --if-absent leaves it alone,
# so re-running that one env reproduces the failure against the same key.
#
# Each is emitted as its PKCS#8 DER (what a test writes to ssh_host_key/priv_der), the bare PKCS#1
# RSAPrivateKey inside it (the other shape the loader accepts), and n, e and d as fixed-width
# big-endian arrays - the independent copy a test builds its expected "ssh-rsa" blob from, rather
# than reading the library's own parsed key back.
#
# Output: test/fixtures/ssh_test_host_key/ssh_test_keys.h, gitignored, rewritten atomically.
#
# Usage:
#   python3 -m tools.crypto.gen_ssh_test_keys           # rewrite the header
#   python3 -m tools.crypto.gen_ssh_test_keys --if-absent  # only when it is not already there

import os
import re
import subprocess
import sys
import tempfile

from tools.ci_tooling.lib import doc_region as dr
from tools.crypto import gen_ssh_host_key as ghk

ROOT = dr.repo_root(__file__)
FIXTURE_DIR = os.path.join(ROOT, "test", "fixtures", "ssh_test_host_key")
BASELINE_H = os.path.join(FIXTURE_DIR, "ssh_test_host_key.h")
OUT = os.path.join(FIXTURE_DIR, "ssh_test_keys.h")


def baseline_der():
    """Pull PROTOCORE_SSH_TEST_HOST_KEY_DER's bytes out of the committed fixture header."""
    with open(BASELINE_H, encoding="utf-8") as f:
        text = f.read()
    body = text.split("PROTOCORE_SSH_TEST_HOST_KEY_DER[] = {", 1)[1].split("};", 1)[0]
    return bytes(int(b, 16) for b in re.findall(r"0x([0-9a-fA-F]{2})", body))


def fresh_der():
    """Generate an RSA-2048 key and return its PKCS#8 DER. The PEM never outlives this call."""
    ghk._need("openssl")
    with tempfile.TemporaryDirectory() as d:
        return ghk.gen_rsa(os.path.join(d, "fresh.pem"))


def emit(name, blob, per=16):
    rows = [", ".join("0x%02x" % b for b in blob[i : i + per]) for i in range(0, len(blob), per)]
    return "static const uint8_t %s[%d] = {\n    %s};\n" % (name, len(blob), ",\n    ".join(rows))


def key_block(prefix, der):
    n, e, d = ghk.rsa_parts(der)
    return "".join(
        [
            emit(prefix + "_DER", der),
            "static const unsigned int %s_DER_LEN = %d;\n" % (prefix, len(der)),
            emit(prefix + "_PKCS1_DER", ghk.rsa_pkcs1(der)),
            "static const unsigned int %s_PKCS1_DER_LEN = %d;\n" % (prefix, len(ghk.rsa_pkcs1(der))),
            emit(prefix + "_N", n),
            emit(prefix + "_E", e),
            emit(prefix + "_D", d),
        ]
    )


def render():
    return "\n".join(
        [
            "// Generated by tools/crypto/gen_ssh_test_keys.py - DO NOT COMMIT.",
            "// The RSA host keys, matching the Ed25519 pairing in test/support/{baseline_keys,throwaway_key}.h:",
            "// PROTOCORE_SSH_BASELINE_KEY_* is the committed fixture key, PROTOCORE_SSH_THROWAWAY_KEY_* is new per run.",
            "// TEST ONLY - both private keys are in plain sight and authenticate nothing.",
            "#pragma once",
            "#include <stdint.h>",
            "",
            key_block("PROTOCORE_SSH_BASELINE_KEY", baseline_der()),
            key_block("PROTOCORE_SSH_THROWAWAY_KEY", fresh_der()),
        ]
    )


def main(argv):
    if "--if-absent" in argv and os.path.exists(OUT):
        return 0
    text = render()
    # Written aside and renamed: a compile that starts mid-write sees the old file or the new one,
    # never half of either.
    fd, tmp = tempfile.mkstemp(dir=FIXTURE_DIR, suffix=".h.tmp")
    with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, OUT)
    print("wrote %s (baseline + throwaway RSA-2048)" % os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
