#!/usr/bin/env python3
"""Generate a deterministic ML-KEM-768 Encaps known-answer vector as a C header for test_pqc_mlkem.

Our server implements only ML-KEM Encaps (responder). To pin a byte-exact known-answer test we need a
trusted, independent FIPS 203 implementation to produce (ek, m) -> (ct, ss) deterministically. This
uses kyber-py (a FIPS 203 reference that tracks the NIST ACVP vectors) with fixed keygen seeds (d, z)
and a fixed encapsulation message m, then cross-checks the shared secret by decapsulating the
ciphertext (round-trip) and, when liboqs is installed, against it too, before emitting the header.

    python3 tools/gen_mlkem_kat.py > test/unit/pqc/test_pqc_mlkem/mlkem_kat.h

Run once and commit the result; the C Encaps must reproduce it byte for byte.
"""

import sys


def emit_array(name, data):
    out = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        row = data[i : i + 12]
        out.append("    " + " ".join(f"0x{b:02x}," for b in row))
    out.append("};")
    return "\n".join(out)


def _encaps(mlkem, ek, m):
    # kyber-py's internal encaps arg order has differed across versions; detect it by output sizes.
    last = None
    for args in ((ek, m), (m, ek)):
        try:
            a, b = mlkem._encaps_internal(*args)
        except Exception as e:  # noqa: BLE001 - probing the right signature
            last = e
            continue
        if len(a) == 32 and len(b) == 1088:
            return a, b
        if len(a) == 1088 and len(b) == 32:
            return b, a
        last = ValueError(f"unexpected encaps output sizes {len(a)}, {len(b)}")
    raise RuntimeError(f"encaps probing failed: {last}")


def main():
    from kyber_py.ml_kem import ML_KEM_768

    d = bytes(range(0, 32))  # fixed keygen seed d
    z = bytes(range(32, 64))  # fixed keygen seed z
    m = bytes((i * 7 + 1) & 0xFF for i in range(32))  # fixed encapsulation message

    ek, dk = ML_KEM_768._keygen_internal(d, z)
    assert len(ek) == 1184 and len(dk) == 2400, f"unexpected key sizes {len(ek)}, {len(dk)}"
    K, ct = _encaps(ML_KEM_768, ek, m)

    # Round-trip: our own decaps must recover K.
    assert ML_KEM_768.decaps(dk, ct) == K, "kyber-py round-trip mismatch"

    # Independent agreement (optional): liboqs uses the same FIPS 203 encodings.
    checked = "kyber-py round-trip"
    try:
        import oqs

        with oqs.KeyEncapsulation("ML-KEM-768", secret_key=bytearray(dk)) as kem:
            assert kem.decap_secret(ct) == K, "liboqs disagreement"
        checked += " + liboqs decaps"
    except Exception as e:  # noqa: BLE001 - liboqs is a nice-to-have cross-check
        checked += f" (liboqs skipped: {e})"

    assert len(ek) == 1184 and len(ct) == 1088 and len(K) == 32

    print("// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>")
    print("// SPDX-License-Identifier: AGPL-3.0-or-later")
    print("//")
    print("// Generated by tools/gen_mlkem_kat.py - deterministic ML-KEM-768 Encaps known-answer vector.")
    print(f"// Oracle: kyber-py (FIPS 203). Cross-checked: {checked}. Do not edit by hand.")
    print("")
    print("#ifndef PC_TEST_MLKEM_KAT_H")
    print("#define PC_TEST_MLKEM_KAT_H")
    print("")
    print("#include <stdint.h>")
    print("")
    print(emit_array("kat_ek", ek))
    print("")
    print(emit_array("kat_dk", dk))
    print("")
    print(emit_array("kat_m", m))
    print("")
    print(emit_array("kat_ct", ct))
    print("")
    print(emit_array("kat_ss", K))
    print("")
    print("#endif")


if __name__ == "__main__":
    sys.exit(main())
