#!/usr/bin/env python3
# Generate + verify the Ed25519 fixed-base comb table (ref10-style signed 4-bit, 32x8) for the
# S3 fe layer, and verify the comb algorithm against an affine reference. Emits a C header of
# extended coords (X, Y, T); Z is implicitly 1. Python is the oracle before any C is written.
import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
from tools.ci_tooling.check.stamp_version import copyright_line  # noqa: E402

p = 2**255 - 19
d = (-121665 * pow(121666, -1, p)) % p
By = (4 * pow(5, -1, p)) % p
# recover Bx (even) from By: x^2 = (y^2 - 1)/(d y^2 + 1)
u = (By * By - 1) % p
v = (d * By * By + 1) % p
xx = (u * pow(v, -1, p)) % p
Bx = pow(xx, (p + 3) // 8, p)
if (Bx * Bx - xx) % p != 0:
    Bx = (Bx * pow(2, (p - 1) // 4, p)) % p
if Bx % 2 != 0:
    Bx = (p - Bx) % p
assert (By * By - Bx * Bx - 1 - d * Bx * Bx * By * By) % p == 0, "B not on curve"
# sanity vs the known encoding: Bx low 32 bits should be 0x8f25d51a (matches ED_X_FE[0])
assert Bx & 0xFFFFFFFF == 0x8F25D51A, hex(Bx & 0xFFFFFFFF)
assert By & 0xFFFFFFFF == 0x66666658, hex(By & 0xFFFFFFFF)

L = 2**252 + 27742317777372353535851937790883648493


# ---- affine group (reference) ----
def aff_add(P, Q):
    if P is None:
        return Q
    if Q is None:
        return P
    x1, y1 = P
    x2, y2 = Q
    dd = (d * x1 * x2 * y1 * y2) % p
    x3 = ((x1 * y2 + x2 * y1) * pow((1 + dd) % p, -1, p)) % p
    y3 = ((y1 * y2 + x1 * x2) * pow((1 - dd) % p, -1, p)) % p
    return (x3, y3)


def aff_mul(k, P):
    R = None
    while k:
        if k & 1:
            R = aff_add(R, P)
        P = aff_add(P, P)
        k >>= 1
    return R


B = (Bx, By)


# ---- recode a 32-byte LE scalar into 64 signed 4-bit digits (ref10) ----
def recode(s):
    e = [0] * 64
    for i in range(32):
        e[2 * i] = s[i] & 15
        e[2 * i + 1] = (s[i] >> 4) & 15
    carry = 0
    for i in range(63):
        e[i] += carry
        carry = (e[i] + 8) >> 4
        e[i] -= carry << 4
    e[63] += carry
    return e  # e[i] in [-8, 8]


# ---- build table[i][j] = (j+1) * 256^i * B (affine) ----
table = [[None] * 8 for _ in range(32)]
Bi = B
for i in range(32):
    acc = None
    for j in range(8):
        acc = aff_add(acc, Bi)  # (j+1)*256^i*B
        table[i][j] = acc
    for _ in range(8):  # Bi *= 256
        Bi = aff_add(Bi, Bi)


def comb_mul(s):
    # returns affine s*B via the comb, using table[] (mirror of the C algorithm)
    e = recode(s)
    R = None
    for i in range(1, 64, 2):  # odd nibbles
        dgt = e[i]
        P = None if dgt == 0 else table[i >> 1][abs(dgt) - 1]
        if dgt < 0 and P is not None:
            P = ((-P[0]) % p, P[1])
        R = aff_add(R, P)
    for _ in range(4):  # x16
        R = aff_add(R, R)
    for i in range(0, 64, 2):  # even nibbles
        dgt = e[i]
        P = None if dgt == 0 else table[i >> 1][abs(dgt) - 1]
        if dgt < 0 and P is not None:
            P = ((-P[0]) % p, P[1])
        R = aff_add(R, P)
    return R


# ---- verify comb vs affine over random scalars incl. clamped-a and r<L ranges ----
random.seed(7)
for _ in range(300):
    kind = random.random()
    if kind < 0.4:
        s = random.randrange(0, L)  # r-style (< L)
    elif kind < 0.8:
        v = random.randrange(0, 1 << 256)  # clamped a-style
        s = (v & ~7) & ((1 << 255) - 1) | (1 << 254)
    else:
        s = random.randrange(0, 1 << 255)
    sb = s.to_bytes(32, "little")
    assert comb_mul(sb) == aff_mul(s, B), f"comb mismatch s={s:x}"
print("Ed25519 comb VERIFIED vs affine over 300 scalars (r<L, clamped-a, random-255).")


# ---- emit the C table header (extended X, Y, T; Z=1 implicit) ----
def words(v):
    return ", ".join("0x%08xu" % ((v >> (32 * k)) & 0xFFFFFFFF) for k in range(8))


lines = []
lines.append(copyright_line())
lines.append("// SPDX-License-Identifier: AGPL-3.0-or-later")
lines.append("//")
lines.append("// GENERATED by tools/crypto/gen_ed25519_comb.py - do not edit by hand.")
lines.append("// Ed25519 fixed-base comb table: ED_COMB[i][j] = (j+1) * 256^i * B, extended (X, Y, T),")
lines.append("// Z implicitly 1. Indexed i in 0..31, j in 0..7. Verified vs an affine reference (RFC 8032 B).")
lines.append("#ifndef PROTOCORE_ED25519_COMB_TABLE_H")
lines.append("#define PROTOCORE_ED25519_COMB_TABLE_H")
lines.append("")
lines.append("static const fe ED_COMB[32][8][3] = {")
for i in range(32):
    lines.append("    {")
    for j in range(8):
        x, y = table[i][j]
        t = (x * y) % p
        lines.append("        {{%s}," % words(x))
        lines.append("         {%s}," % words(y))
        lines.append("         {%s}}," % words(t))
    lines.append("    },")
lines.append("};")
lines.append("")
lines.append("#endif")
_here = os.path.dirname(os.path.abspath(__file__))
_out = os.path.join(_here, "..", "..", "src", "crypto", "asymmetric", "ed25519_comb_table.h")
with open(_out, "w", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print("wrote %s (%d entries)" % (_out, 32 * 8))
