// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by src/web_assets/wizard/gen_theme_blobs.py - DO NOT EDIT BY HAND.
// Add or edit a theme under src/web_assets/themes/ and re-run the generator.

/**
 * @file binary_asset_blobs.h
 * @brief Layer 7 - toggleable embedded theme stylesheets (PROTOCORE_ENABLE_THEMES).
 *
 * A registry of minified CSS themes in flash (DROM), for serving/switching a theme at runtime.
 * Behind PROTOCORE_ENABLE_THEMES so a build that does not want it links nothing.
 */

#ifndef PROTOCORE_BINARY_ASSET_BLOBS_H
#define PROTOCORE_BINARY_ASSET_BLOBS_H

#include "protocore_config.h" // the entry point: protocore_types.h for the widths

#if PROTOCORE_ENABLE_THEMES

PROTOCORE_BEGIN_DECLS

// This module holds nothing between calls, so it carves no borrow and states none. An entry
// takes one all the same, and never reads it, so every namespace in the tree is invoked the
// same way.

/** @brief What css takes: name. */
typedef struct
{
    const char *name;
} BinaryAssetBlobsCssArgs;
/** @brief The embedded theme registry (sorted by name) and its count. */
extern const protocore_theme_blob PROTOCORE_THEME_BLOBS[];
extern const size_t PROTOCORE_THEME_BLOB_COUNT;
/**
 * @brief Layer 7 - toggleable embedded theme stylesheets (PROTOCORE_ENABLE_THEMES).
 *
 * A caller sets the members a call takes, invokes it through ::BinaryAssetBlobs with the bytes it runs
 * out of, and reads the outcome off the same handle.
 *
 *   BinaryAssetBlobs.css_args.name = ...;
 *   BinaryAssetBlobs.css(work);
 *   // BinaryAssetBlobs.text is what the call reports
 *
 * @var BinaryAssetBlobsNs::css_args  what css takes: name
 * @var BinaryAssetBlobsNs::ok  a call's true/false outcome
 * @var BinaryAssetBlobsNs::text  the NUL-terminated minified CSS, or nullptr if no theme by that ...
 * @var BinaryAssetBlobsNs::css  look up a theme's CSS by name (exact match)
 *
 * @c work is bytes the CALLER holds. This module reads none of them: it carries nothing
 * between calls, so there is no state to keep and nothing to wipe. The parameter is there so
 * a caller drives every namespace the same way.
 */
typedef struct
{
    BinaryAssetBlobsCssArgs css_args;
    proto_bool ok;
    const char *text;
} BinaryAssetBlobsVars;

/** @brief The operands and the outcome. */
extern BinaryAssetBlobsVars BinaryAssetBlobsV;

/** @brief The entries. */
typedef struct
{
    void (*const css)(uint8_t *restrict work);
} BinaryAssetBlobsNs;

// What the table binds, defined once in the .c and taking one parameter each: everything
// else an entry needs is an operand in BinaryAssetBlobsV or a region of the borrow at a fixed offset.
void protocore_binary_asset_blobs_css(uint8_t *restrict work);

// `static const`, initialised HERE rather than `extern` against a definition in the .c: a
// const object whose initializer every translation unit can see is a COMPILE-TIME FACT, so
// `BinaryAssetBlobs.css(work)` resolves to a named function and becomes a DIRECT call. An extern table
// leaves the call indirect and the symbol live at every level, -O2 -flto included.
static const BinaryAssetBlobsNs BinaryAssetBlobs __attribute__((unused)) = {
    .css = protocore_binary_asset_blobs_css,
};

PROTOCORE_END_DECLS

#endif // PROTOCORE_ENABLE_THEMES

#endif // PROTOCORE_BINARY_ASSET_BLOBS_H
