// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by src/web_assets/wizard/gen_theme_blobs.py - DO NOT EDIT BY HAND.
// Add or edit a theme under src/web_assets/themes/ and re-run the generator.

#ifndef PROTOCORE_BINARY_ASSET_BLOBS_H
#define PROTOCORE_BINARY_ASSET_BLOBS_H

#include "protocore_config.h" // the entry point: protocore_types.h for the widths

PROTOCORE_BEGIN_DECLS

/**
 * @file binary_asset_blobs.h
 * @brief Layer 7 - toggleable embedded theme stylesheets (PROTOCORE_ENABLE_THEMES).
 *
 * A registry of minified CSS themes in flash (DROM), for serving/switching a theme at runtime.
 * Behind PROTOCORE_ENABLE_THEMES so a build that does not want it links nothing.
 *
 * @c work is bytes the CALLER holds. This module reads none of them: it carries nothing
 * between calls, so there is no state to keep and nothing to wipe. The parameter is there so
 * a caller drives every namespace the same way.
 */

// PROTOCORE_BINARY_ASSET_BLOBS_BORROW - the bytes this module runs out of - is stated in protocore_config.h, which sums
// it into its arena. Its size and its offset are each a static_assert, so a feature
// combination that does not fit fails to compile rather than overrunning at run time.

/** @brief The embedded theme registry (sorted by name) and its count. */
extern const protocore_theme_blob PROTOCORE_THEME_BLOBS[];

extern const size_t PROTOCORE_THEME_BLOB_COUNT;

/** @brief Dispatch table. Addressed by offset, so the layout is asserted below. */
typedef struct
{
    void (*css)(uint8_t *restrict, const char *);
} BinaryAssetBlobsNs;
PROTOCORE_NS_LAYOUT(BinaryAssetBlobsNs, css);

/**
 * @brief Look up a theme's CSS by name (exact match).
 * @param work PROTOCORE_BINARY_ASSET_BLOBS_BORROW bytes the caller took. Not held past the call.
 * @param name Name
 */
void protocore_binary_asset_blobs_css(uint8_t *restrict work, const char *name);

/** @brief Module namespace. */
PROTOCORE_NS BinaryAssetBlobsNs BinaryAssetBlobs PROTOCORE_UNUSED = {.css = protocore_binary_asset_blobs_css};

PROTOCORE_END_DECLS

#endif // PROTOCORE_BINARY_ASSET_BLOBS_H
