#!/usr/bin/env python3
# ProtoCore v1.0.16 - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Layering guard: fail if a file includes a header from a higher layer.

The stack is the one in docs/ARCHITECTURE.md, and it runs one way: a layer includes what is
below it and publishes to what is above. An include that points up is either a layering
violation or a misfiled file, and both read the same way here - the edge is what is wrong,
not which of the two caused it.

The whole graph is the text, so no compiler runs and no env is built. Conditional includes are
followed rather than skipped: the preprocessor nesting is tracked line by line, so an edge that
exists only under PROTOCORE_ENABLE_X is reported carrying that guard instead of being invisible. An
edge is a violation if it exists under any configuration, because a build that turns the flag
on gets the edge.

The layer of a file is the longest directory prefix that matches; a file under no listed prefix
(protocore.h, protocore_config.h, the generated web assets) has no layer and is skipped, since
the root header is above everything by construction.
"""

import os
import re
import sys
from pathlib import Path

from tools.ci_tooling.lib import baseline as bl
from tools.ci_tooling.lib import doc_region as dr

# Walks up to the root markers rather than counting directory levels, so moving this file does
# not silently point it at a directory that does not exist.
ROOT = Path(dr.repo_root(__file__))
SRC = ROOT / "src"
# protocore.h is the library entry header and sits in include/, beside src/ rather than in it. It is
# what pulls in most of the module headers, so a walk that skips it reports them all as unincluded.
ENTRY = ROOT / "include"
# core_setup/ sits beside src/ too, and every include of it writes that prefix, so its headers are
# keyed from the repo root. They carry a layer for resolve() and are not walked as sources.
SETUP = ROOT / "core_setup"

BASELINE = bl.path_for(__file__, "layering_baseline")

# Low to high. The number is the rank an include may not increase.
LAYERS = (
    ("core_setup/", 0),
    ("shared/", 1),
    ("mmgr/", 2),
    ("crypto/", 3),
    ("network_drivers/physical/", 4),
    ("network_drivers/datalink/", 5),
    ("network_drivers/network/", 6),
    ("network_drivers/transport/", 7),
    ("network_drivers/tls/", 8),
    ("server/core/", 9),
    # The session layer uses the server core rather than being part of it, so it ranks with it:
    # session may include the core, and an equal rank is what permits that.
    ("network_drivers/session/", 9),
    ("network_drivers/presentation/", 10),
    ("network_drivers/application/", 11),
    ("services/", 12),
    ("server/", 13),
)

SKIP_DIRS = {"web_assets", "__pycache__"}

# A header nothing includes is dead until someone says why it is not. Each entry carries the
# reason, because "it is in the list" is not one and an unexplained entry is how a genuinely dead
# file survives a sweep. Add a header here only with the sentence that justifies it.
ORPHAN_ALLOW = {
    "network_drivers/application/binary_asset_blobs.h": (
        "generated by src/web_assets/wizard/gen_theme_blobs.py; the blobs land before the route that serves them"
    ),
    "network_drivers/tls/handshake/handshake.h": (
        "SW TLS server handshake driver, landed ahead of the software arm that will call it"
    ),
    "server/peripherals/pmbus.h": (
        "peripheral API with its own env compiling pmbus.c; no in-tree caller until a board wants it"
    ),
    "network_drivers/datalink/datalink.h": (
        "the L2 seam the real datalink functions extend; no env or caller yet - native_datalink is owed"
    ),
}

INCLUDE = re.compile(r'^\s*#\s*include\s*"([^"]+)"')
COND_OPEN = re.compile(r"^\s*#\s*(if|ifdef|ifndef)\b\s*(.*)")
COND_MID = re.compile(r"^\s*#\s*(elif|else)\b\s*(.*)")
COND_END = re.compile(r"^\s*#\s*endif\b")

# An include guard is the file's own name, so it is not a configuration branch and naming it in
# the report would bury the real guard under noise.
GUARD_NAME = re.compile(r"^PROTOCORE_\w+_H$")


def layer_of(rel):
    """(rank, prefix) for the longest matching prefix, or (-1, "") when the file has no layer."""
    rank, pref = -1, ""
    for p, n in LAYERS:
        if rel.startswith(p) and len(p) > len(pref):
            rank, pref = n, p
    return rank, pref


def resolve(inc, from_rel, known):
    """The src-relative path an include names, or None when it leaves the tree.

    C resolves a quoted include against the including file's own directory first, so a sibling
    reached as "../tcp/evt.h" is the same file as "network_drivers/transport/tcp/evt.h".
    Matching the literal text alone makes every relative include invisible.
    """
    local = os.path.normpath(os.path.join(os.path.dirname(from_rel), inc)).replace(os.sep, "/")
    if local in known:
        return local
    if inc in known:
        return inc
    return None


def sources():
    for dirpath, dirs, files in os.walk(SRC):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for fn in sorted(files):
            if fn.endswith((".c", ".h")):
                p = Path(dirpath) / fn
                yield str(p.relative_to(SRC)).replace(os.sep, "/"), p
    # The entry header names its includes as src-relative paths, so it is walked with the same
    # relative root; its own name is not a layer and never appears as an include target.
    for fn in sorted(os.listdir(ENTRY)) if ENTRY.is_dir() else []:
        if fn.endswith((".c", ".h")):
            yield fn, ENTRY / fn


def setup_headers():
    """core_setup/ headers, keyed from the repo root, which is the path an include of one names."""
    for dirpath, dirs, files in os.walk(SETUP):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for fn in sorted(files):
            if fn.endswith(".h"):
                p = Path(dirpath) / fn
                yield str(p.relative_to(ROOT)).replace(os.sep, "/"), p


def edges_of(path):
    """((included, line, guard) list, unbalanced list) - the conditional nesting is tracked here.

    `unbalanced` carries an #endif that closed nothing and any #if still open at the end of the
    file, which is what makes a guard read as covering text it does not cover.
    """
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return [], []
    out = []
    bad = []
    stack = []
    for i, line in enumerate(text.splitlines(), 1):
        m = COND_OPEN.match(line)
        if m:
            cond = m.group(2).strip().split("//")[0].strip()
            stack.append(("" if GUARD_NAME.match(cond) else cond, i))
            continue
        m = COND_MID.match(line)
        if m:
            if stack:
                cond = m.group(2).strip().split("//")[0].strip()
                prev, at = stack[-1]
                stack[-1] = (cond if m.group(1) == "elif" else "!(%s)" % (prev or "?"), at)
            else:
                bad.append((i, "#%s with no open #if" % m.group(1)))
            continue
        if COND_END.match(line):
            if stack:
                stack.pop()
            else:
                bad.append((i, "#endif with no open #if"))
            continue
        m = INCLUDE.match(line)
        if m:
            guard = " && ".join(c for c, _ in stack if c)
            out.append((m.group(1), i, guard))
    for cond, at in stack:
        bad.append((at, "#if never closed: %s" % (cond or "(include guard)")))
    return out, bad


def main(argv):
    known_files = {}
    for rel, path in sources():
        known_files[rel] = path
    # What an include may name: the walked sources plus the core_setup/ headers under them.
    targets = dict(known_files)
    for rel, path in setup_headers():
        targets.setdefault(rel, path)

    findings = []
    broken = []
    included_by = {rel: set() for rel in targets}
    for rel, path in sorted(known_files.items()):
        edges, bad = edges_of(path)
        for line, why in bad:
            broken.append((rel, line, why))
        rank, _ = layer_of(rel)
        for inc, line, guard in edges:
            target = resolve(inc, rel, targets)
            if target is None:
                continue  # a toolchain or vendor header carries no layer
            included_by[target].add(rel)
            irank, _ = layer_of(target)
            if rank >= 0 and irank > rank:
                findings.append((rel, target, rank, irank, line, guard))

    # A .c is compiled by a build filter, not included, so only headers can be orphans. A header's
    # own .c does not count as reaching it: every implementation includes its own header, so
    # counting that pair makes a dead module look connected to itself.
    orphans = []
    for rel in sorted(known_files):
        if not rel.endswith(".h") or rel in ORPHAN_ALLOW:
            continue
        outside = included_by[rel] - {rel[:-2] + ".c"}
        if not outside:
            orphans.append(rel)

    # Keyed on the pair alone. A line number would resurrect a known edge every time something
    # above it moved, and the same pair under two guards is one relationship, not two.
    def key_of(f):
        return "%s -> %s" % (f[0], f[1])

    if "--baseline" in argv:
        n = bl.save(BASELINE, (key_of(f) for f in findings))
        print("check_layering: recorded %d known upward include(s) as the floor" % n)
        return 0

    new, known, fixed = bl.filter_new(findings, key_of, BASELINE)

    if "--list" in argv:
        for rel, inc, rank, irank, line, guard in sorted(findings, key=lambda f: f[3] - f[2], reverse=True):
            tag = ("  [%s]" % guard) if guard else ""
            print("  L%-2d -> L%-2d  %s:%d -> %s%s" % (rank, irank, rel, line, inc, tag))
        print("\n%d upward include(s)" % len(findings))
        print("\n%d header(s) nothing includes:" % len(orphans))
        for rel in orphans:
            print("  %s" % rel)
        print("\n%d unbalanced conditional(s):" % len(broken))
        for rel, line, why in broken:
            print("  src/%s:%d: %s" % (rel, line, why))
        return 0

    # Both of these are defects on sight rather than a ratcheted floor: an unbalanced conditional
    # makes every guard below it wrong, and an orphan is either dead or needs one sentence.
    if broken:
        print("Layering guard: unbalanced preprocessor conditional(s):\n")
        for rel, line, why in broken:
            print("  src/%s:%d: %s" % (rel, line, why))
        print(
            "\n%d unbalanced conditional(s). Every #if guard after one of these covers text it "
            "does not appear to cover, so the file's include set cannot be read." % len(broken)
        )
        return 1

    if orphans:
        print("Layering guard: header(s) nothing under src/ includes:\n")
        for rel in orphans:
            print("  src/%s" % rel)
        print(
            "\n%d unincluded header(s). Each is either dead and gets deleted, or it is reached "
            "some other way - a library entry header the application includes, a board seam the "
            "build filter selects, a public API not used until a caller wants it. Justify each in "
            "ORPHAN_ALLOW in tools/ci_tooling/check/check_layering.py, with the sentence that "
            "makes it not dead." % len(orphans)
        )
        return 1

    if new:
        print("Layering guard: include(s) pointing up the stack:\n")
        for rel, inc, rank, irank, line, guard in new:
            tag = ("  [under %s]" % guard) if guard else ""
            print("  src/%s:%d: L%d includes L%d  ->  %s%s" % (rel, line, rank, irank, inc, tag))
        print(
            "\n%d new upward include(s). A layer includes what is below it, never above: move the "
            "dependency down, or move the file to the layer it actually belongs to (a TLS header "
            "filed under http3/ is the second shape, and moving the file is the whole fix). If the "
            "layer table itself is wrong, correct LAYERS in "
            "tools/ci_tooling/check/check_layering.py rather than recording the edge." % len(new)
        )
        return 1

    # Every exemption, every run. An allow-list nobody reads is how a dead file lives forever, and
    # the reason is printed next to it so a stale one is obvious the moment it stops being true.
    if ORPHAN_ALLOW:
        print("Layering guard: %d header(s) allowed to be unincluded:" % len(ORPHAN_ALLOW))
        for rel in sorted(ORPHAN_ALLOW):
            print("  src/%-58s %s" % (rel, ORPHAN_ALLOW[rel]))
        print("")

    tail = ""
    if known:
        tail = " (%d known upward include(s) remain%s)" % (known, ", %d fixed" % fixed if fixed else "")
    print("Layering guard: OK - no new upward includes%s." % tail)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
