#!/usr/bin/env python3
# ProtoCore v1.0.16 - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
"""The version a source file was last edited against, carried on its copyright line.

A release bump rewrites the nine sites in .bumpversion.cfg and nothing else, so a file's own
history is invisible: nothing in it says which release its current contents belong to. The stamp
records that. It is written by the pre-commit hook onto the files a commit touches, so it moves
per file rather than per release, and a file that has not changed since v1.0.9 still says so.

The stamp goes in front of the copyright, which every owned source file already carries as its
first or second line:

    // ProtoCore v1.0.16 - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
    # ProtoCore v1.0.16 - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
    <!-- ProtoCore v1.0.16 - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com> -->

Inserting before `Copyright` keeps whatever comment syntax the file already opened with, so C,
Python, shell, markdown, linker scripts and assembly all take the same edit with no per-type table.

Scope is scripts and source under src/, test/, test/core_setup/, include/ and tools/. Build output,
__pycache__ and vendored trees are not source. Generated files carry a stamp emitted by their
generator, so this tool skips them rather than writing a stamp the next regeneration would drop.

Modes:
  --list    print the scope, and what is skipped and why
  --check   every in-scope file carries a well-formed stamp (exit 1 otherwise)
  --write   write the current version onto the named files, or all in-scope files if none named
"""

import argparse
import configparser
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
CFG = os.path.join(ROOT, ".bumpversion.cfg")

SCOPE_DIRS = ("src", "test", "vendor", "include", "tools")
SKIP_DIRS = {
    ".git",
    ".pio",
    ".pio_cov",
    "__pycache__",
    "node_modules",
    "managed_components",
    "build",
    "build-lto",
    "coverage_reports",
    ".mypy_cache",
    ".ruff_cache",
    "dist",
}
# Compiled and concatenated output that carries the copyright only because its input did.
SKIP_EXTS = {".pyc", ".pyo", ".merged", ".bin", ".elf", ".o", ".a"}

OWNER = "Copyright (C) 2026 Douglas Quigg"
COPYRIGHT = OWNER + " (dstroy0) <dquigg123@gmail.com>"
# The stamp, and the copyright it sits in front of. Group `pre` keeps the comment opener.
STAMP_RE = re.compile(r"^(?P<pre>.*?)(?:ProtoCore v(?P<ver>\d+\.\d+\.\d+) - )?(?P<cr>" + re.escape(OWNER) + r")")
# A generator owns its output's stamp; a stamp written here dies at the next regeneration. The
# do-not-edit warning is the marker: prose about generating something does not carry one.
GEN_RE = re.compile(r"DO NOT EDIT|AUTOGENERATED", re.IGNORECASE)
GEN_LOOKAHEAD = 8
# A file's own copyright opens it, after at most a shebang and a comment line or two. A generator
# that emits a copyright into its output holds that text in a string much further down, and that
# string is the output's stamp to carry, not this file's.
HEADER_WINDOW = 10


def read(path):
    with io.open(path, encoding="utf-8", errors="ignore", newline="") as f:
        return f.read()


def current_version():
    cp = configparser.ConfigParser()
    cp.read(CFG, encoding="utf-8")
    return cp["bumpversion"]["current_version"].strip()


def copyright_line(prefix="// ", ver=None):
    """The stamped copyright line a generator writes at the top of its output."""
    return "%sProtoCore v%s - %s" % (prefix, ver or current_version(), COPYRIGHT)


def classify(path):
    """(state, first_stamp_line_index) where state is owned / generated / unowned."""
    try:
        text = read(path)
    except (OSError, ValueError):
        return "unowned", -1, ""
    if OWNER not in text:
        return "unowned", -1, text
    lines = text.split("\n")
    if GEN_RE.search("\n".join(lines[:GEN_LOOKAHEAD])):
        return "generated", -1, text
    for i, line in enumerate(lines[:HEADER_WINDOW]):
        if OWNER in line:
            return "owned", i, text
    return "unowned", -1, text


def walk():
    for top in SCOPE_DIRS:
        base = os.path.join(ROOT, top)
        if not os.path.isdir(base):
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for fn in filenames:
                if os.path.splitext(fn)[1].lower() in SKIP_EXTS:
                    continue
                yield os.path.join(dirpath, fn)


def rel(path):
    return os.path.relpath(path, ROOT).replace("\\", "/")


def stamp_text(text, idx, ver):
    """Rewrite line `idx` so the copyright carries the stamp. Returns None when unchanged."""
    lines = text.split("\n")
    m = STAMP_RE.match(lines[idx])
    if not m:
        return None
    new = "%sProtoCore v%s - %s%s" % (m.group("pre"), ver, m.group("cr"), lines[idx][m.end() :])
    if new == lines[idx]:
        return None
    lines[idx] = new
    return "\n".join(lines)


def write(path, text):
    with io.open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--list", action="store_true", help="print the scope and what is skipped")
    g.add_argument("--check", action="store_true", help="every in-scope file carries a stamp")
    g.add_argument("--write", action="store_true", help="write the current version onto files")
    ap.add_argument("files", nargs="*", help="paths to stamp; default is every in-scope file")
    ap.add_argument("-q", "--quiet", action="store_true", help="print nothing when clean")
    a = ap.parse_args()

    ver = current_version()

    if a.files:
        paths = [os.path.abspath(p) for p in a.files]
    else:
        paths = list(walk())

    owned, generated = [], []
    for p in paths:
        state, idx, text = classify(p)
        if state == "owned":
            owned.append((p, idx, text))
        elif state == "generated":
            generated.append(p)

    if a.list:
        print("version %s" % ver)
        print("in scope (owned source): %d" % len(owned))
        print("generated, stamped by their generator: %d" % len(generated))
        for p in sorted(generated):
            print("  %s" % rel(p))
        return 0

    if a.check:
        bad = []
        for p, idx, text in owned:
            m = STAMP_RE.match(text.split("\n")[idx])
            if not m or not m.group("ver"):
                bad.append(rel(p))
        if bad:
            print("files missing a version stamp (%d):" % len(bad), file=sys.stderr)
            for b in sorted(bad)[:40]:
                print("  " + b, file=sys.stderr)
            if len(bad) > 40:
                print("  ... and %d more" % (len(bad) - 40), file=sys.stderr)
            print("run: python tools/ci_tooling/check/stamp_version.py --write", file=sys.stderr)
            return 1
        if not a.quiet:
            print("all %d in-scope files carry a version stamp." % len(owned))
        return 0

    changed = 0
    for p, idx, text in owned:
        new = stamp_text(text, idx, ver)
        if new is not None:
            write(p, new)
            changed += 1
    if not a.quiet:
        print(
            "stamped %d file(s) at v%s (%d already current, %d generated skipped)"
            % (changed, ver, len(owned) - changed, len(generated))
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
