#!/usr/bin/env python3
# ProtoCore v1.0.16 - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Embed the theme stylesheets as toggleable binary asset blobs in Layer 7.

The themes under src/web_assets/themes/{,generated/} are normally injected into a page at build time. This
generator instead embeds them - minified - as `const char[]` blobs in a registry so the firmware can
serve or switch a theme at runtime (e.g. a `/themes/<name>.css` route, or a picker that remembers the
user's choice). The whole subsystem is behind `PROTOCORE_ENABLE_THEMES`, so a build that does not want
runtime theming links none of it; enabling it embeds the set (each theme is ~1 KB of DROM/flash).

Output: src/network_drivers/application/binary_asset_blobs/binary_asset_blobs.{h,c} (generated + committed, so the
Arduino-IDE users who never run Python still get it). Re-run after adding/editing a theme.

    python -m src.web_assets.wizard.gen_theme_blobs            # regenerate
    python -m src.web_assets.wizard.gen_theme_blobs --check    # CI: fail if stale
"""

import os
import re
import sys

from tools import findroot
from src.web_assets.wizard import gen_themes

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = findroot.root()

THEMES_DIRS = [
    os.path.normpath(os.path.join(SCRIPT_DIR, "..", "themes")),
    os.path.normpath(os.path.join(SCRIPT_DIR, "..", "themes", "generated")),
]
OUT_DIR = os.path.join(REPO_ROOT, "src", "network_drivers", "application", "binary_asset_blobs")
BASENAME = "binary_asset_blobs"

BANNER = (
    "// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>\n"
    "// SPDX-License-Identifier: AGPL-3.0-or-later\n"
    "//\n"
    "// GENERATED by src/web_assets/wizard/gen_theme_blobs.py - DO NOT EDIT BY HAND.\n"
    "// Add or edit a theme under src/web_assets/themes/ and re-run the generator."
)

# The trademark-named themes - their blobs are gated for commercial.
RESTRICTED = set(gen_themes.RESTRICTED)


def minify_css(css):
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.DOTALL)
    css = re.sub(r"\s+", " ", css)
    css = re.sub(r"\s*([{}:;,>])\s*", r"\1", css)
    return css.strip()


_SIMPLE = {"\\": "\\\\", '"': '\\"', "\n": "\\n", "\r": "\\r", "\t": "\\t"}


def escape_segments(text, width=110):
    segs, cur = [], ""
    for ch in text:
        tok = _SIMPLE.get(ch) or ('\\x%02x""' % ord(ch) if ord(ch) < 0x20 else ch)
        if len(cur) + len(tok) > width and cur:
            segs.append(cur)
            cur = ""
        cur += tok
    if cur or not segs:
        segs.append(cur)
    return segs


def c_ident(name):
    return "PROTOCORE_THEME_" + re.sub(r"[^A-Za-z0-9]", "_", name).upper()


def load_themes():
    """Return [(name, minified_css)] for every theme, sorted; a generated/<n> keeps its bare name."""
    seen = {}
    for d in THEMES_DIRS:
        if not os.path.isdir(d):
            continue
        for f in sorted(os.listdir(d)):
            if not f.endswith(".css"):
                continue
            name = f[:-4]
            with open(os.path.join(d, f), encoding="utf-8") as fh:
                seen[name] = minify_css(fh.read())
    return sorted(seen.items())


def render_header(themes):
    guard = "PROTOCORE_BINARY_ASSET_BLOBS_H"
    lines = [
        BANNER,
        "",
        "#ifndef " + guard,
        "#define " + guard,
        "",
        '#include "protocore_config.h" // the entry point: protocore_types.h for the widths',
        "",
        "PROTOCORE_BEGIN_DECLS",
        "",
        "/**",
        " * @file binary_asset_blobs.h",
        " * @brief Layer 7 - toggleable embedded theme stylesheets (PROTOCORE_ENABLE_THEMES).",
        " *",
        " * A registry of minified CSS themes in flash (DROM), for serving/switching a theme at runtime.",
        " * Behind PROTOCORE_ENABLE_THEMES so a build that does not want it links nothing.",
        " *",
        " * @c work is bytes the CALLER holds. This module reads none of them: it carries nothing",
        " * between calls, so there is no state to keep and nothing to wipe. The parameter is there so",
        " * a caller drives every namespace the same way.",
        " */",
        "",
        "/** @brief One embedded theme: its name and its minified CSS (NUL-terminated flash string). */",
        "typedef struct",
        "{",
        "    const char *name;",
        "    const char *css;",
        "} protocore_theme_blob;",
        "",
        "/** @brief The embedded theme registry (sorted by name) and its count. */",
        "extern const protocore_theme_blob PROTOCORE_THEME_BLOBS[];",
        "",
        "extern const size_t PROTOCORE_THEME_BLOB_COUNT;",
        "",
        "/** @brief Dispatch table. Addressed by offset, so the layout is asserted below. */",
        "typedef struct",
        "{",
        "    const char *(*css)(uint8_t *, const char *);",
        "} BinaryAssetBlobsNs;",
        "PROTOCORE_NS_LAYOUT(BinaryAssetBlobsNs, css);",
        "",
        "/**",
        " * @brief Look up a theme's CSS by name (exact match).",
        " * @param work Bytes the caller holds. Not read.",
        " * @param name The theme name, NUL-terminated.",
        " * @return The NUL-terminated minified CSS, or NULL where no theme by that name is embedded.",
        " */",
        "const char *protocore_binary_asset_blobs_css(uint8_t *work, const char *name);",
        "",
        "/** @brief Module namespace. */",
        "PROTOCORE_NS BinaryAssetBlobsNs BinaryAssetBlobs PROTOCORE_UNUSED = {.css = protocore_binary_asset_blobs_css};",
        "",
        "PROTOCORE_END_DECLS",
        "",
        "#endif // " + guard,
    ]
    return "\n".join(lines) + "\n"


def render_source(themes):
    name_cap = max((len(name) for name, _ in themes), default=0) + 1
    lines = [
        BANNER,
        "",
        '#include "protocore_config.h" // the entry point: the widths',
        "",
        '#include "binary_asset_blobs.h"',
        '#include "mmgr/protostr/protostr.h"',
        "",
        "#if PROTOCORE_ENABLE_THEMES",
        "",
        "// One past the longest embedded name. A name that reaches it is longer than every theme, so",
        "// the length scan stops there and nothing matches.",
        "#define THEME_NAME_CAP %du" % name_cap,
        "",
        "PROTOCORE_BEGIN_DECLS",
        "",
    ]
    for name, css in themes:
        segs = escape_segments(css)
        restricted = name in RESTRICTED
        if restricted:  # a trademark-named theme: keep it in OSS, drop it from a commercial build
            lines.append("#if PROTOCORE_THEMES_INCLUDE_TRADEMARKED")
        lines.append("static const char %s[] =" % c_ident(name))
        lines.append('    "' + '"\n    "'.join(segs) + '";')
        if restricted:
            lines.append("#endif")
        lines.append("")
    lines.append("const protocore_theme_blob PROTOCORE_THEME_BLOBS[] = {")
    for name, _ in themes:
        if name in RESTRICTED:
            lines.append("#if PROTOCORE_THEMES_INCLUDE_TRADEMARKED")
            lines.append('    {"%s", %s},' % (name, c_ident(name)))
            lines.append("#endif")
        else:
            lines.append('    {"%s", %s},' % (name, c_ident(name)))
    lines.append("};")
    # sizeof so the count stays correct whether or not the trademark-gated entries are compiled in.
    lines.append(
        "const size_t PROTOCORE_THEME_BLOB_COUNT = sizeof(PROTOCORE_THEME_BLOBS) / sizeof(PROTOCORE_THEME_BLOBS[0]);"
    )
    lines += [
        "",
        "const char *protocore_binary_asset_blobs_css(uint8_t *work, const char *name)",
        "{",
        "    (void)work;",
        "",
        "    if (name == NULL)",
        "    {",
        "        return NULL;",
        "    }",
        "    // str.eq reads read_cap bytes of both operands, so the lengths are matched first: two",
        "    // strings of length n each hold n + 1 readable bytes, the terminator included.",
        "    const size_t n = str.len(name, THEME_NAME_CAP);",
        "    for (size_t i = 0; i < PROTOCORE_THEME_BLOB_COUNT; i++)",
        "    {",
        "        const char *have = PROTOCORE_THEME_BLOBS[i].name;",
        "        if (str.len(have, THEME_NAME_CAP) == n && str.eq(have, name, n + 1u, PROTO_FALSE))",
        "        {",
        "            return PROTOCORE_THEME_BLOBS[i].css;",
        "        }",
        "    }",
        "    return NULL;",
        "}",
        "",
        "PROTOCORE_END_DECLS",
        "",
        "#endif // PROTOCORE_ENABLE_THEMES",
    ]
    return "\n".join(lines) + "\n"


def generate(write=True):
    themes = load_themes()
    files = {
        os.path.join(OUT_DIR, BASENAME + ".h"): render_header(themes),
        os.path.join(OUT_DIR, BASENAME + ".c"): render_source(themes),
    }
    stale = []
    for path, content in files.items():
        old = open(path, encoding="utf-8", newline="").read() if os.path.isfile(path) else None
        if old != content:
            stale.append(findroot.rel(path))
            if write:
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(content)
    return themes, stale


def main():
    check = "--check" in sys.argv[1:]
    themes, stale = generate(write=not check)
    if check:
        if stale:
            sys.stderr.write("STALE (run gen_theme_blobs.py): " + ", ".join(stale) + "\n")
            return 1
        print(f"{len(themes)} theme blobs in sync")
        return 0
    print(f"embedded {len(themes)} theme blobs" + (f" ({', '.join(stale)} changed)" if stale else " (up to date)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
