// ProtoCore v1.0.16 - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

#ifndef PROTOCORE_CONFIG_H
#define PROTOCORE_CONFIG_H

// The platform: the vendor axis, the board profile, the widths, the primitive types built from
// them, and the capability questions the target had to answer. Reached first because every knob
// below is stated in those types and gated on those capabilities.
#include "config/platform/platform.h"

#ifndef PROTOCORE_ENABLE_DIFFSERV
#define PROTOCORE_ENABLE_DIFFSERV 0
#endif

#ifndef PROTOCORE_ENABLE_PREEMPT_QUEUE
#define PROTOCORE_ENABLE_PREEMPT_QUEUE 0
#endif

#ifndef PROTOCORE_ENABLE_DMA
#define PROTOCORE_ENABLE_DMA 0
#endif

#ifndef PROTOCORE_ENABLE_TRACE_CAPTURE
#define PROTOCORE_ENABLE_TRACE_CAPTURE 0
#endif

#ifndef PROTOCORE_ENABLE_AD9238
#define PROTOCORE_ENABLE_AD9238 0
#endif

#ifndef PROTOCORE_ENABLE_FORWARD
#define PROTOCORE_ENABLE_FORWARD 0
#endif

#ifndef PROTOCORE_ENABLE_GATEWAY
#define PROTOCORE_ENABLE_GATEWAY 0
#endif

#ifndef PROTOCORE_ENABLE_LORA
#define PROTOCORE_ENABLE_LORA 0
#endif

#ifndef PROTOCORE_ENABLE_NRF24
#define PROTOCORE_ENABLE_NRF24 0
#endif

#ifndef PROTOCORE_ENABLE_ENOCEAN
#define PROTOCORE_ENABLE_ENOCEAN 0
#endif

#ifndef PROTOCORE_ENABLE_PN532
#define PROTOCORE_ENABLE_PN532 0
#endif

#ifndef PROTOCORE_ENABLE_SIGFOX
#define PROTOCORE_ENABLE_SIGFOX 0
#endif

#ifndef PROTOCORE_ENABLE_ZWAVE
#define PROTOCORE_ENABLE_ZWAVE 0
#endif

#ifndef PROTOCORE_ENABLE_ZIGBEE
#define PROTOCORE_ENABLE_ZIGBEE 0
#endif

#ifndef PROTOCORE_ENABLE_THREAD
#define PROTOCORE_ENABLE_THREAD 0
#endif

#ifndef PROTOCORE_ENABLE_ETHERNET
#define PROTOCORE_ENABLE_ETHERNET 0
#endif

#ifndef PROTOCORE_ENABLE_IPV6
#define PROTOCORE_ENABLE_IPV6 0
#endif

#ifndef PROTOCORE_ENABLE_PROMISC
#define PROTOCORE_ENABLE_PROMISC 0
#endif

#ifndef PROTOCORE_ENABLE_BUS_CAPTURE
#define PROTOCORE_ENABLE_BUS_CAPTURE 0
#endif

#ifndef PROTOCORE_ENABLE_WEBSOCKET
#define PROTOCORE_ENABLE_WEBSOCKET 0
#endif

#ifndef PROTOCORE_ENABLE_WS_DEFLATE
#define PROTOCORE_ENABLE_WS_DEFLATE 0
#endif

#ifndef PROTOCORE_ENABLE_SSE
#define PROTOCORE_ENABLE_SSE 0
#endif

#ifndef PROTOCORE_ENABLE_MULTIPART
#define PROTOCORE_ENABLE_MULTIPART 0
#endif

#ifndef PROTOCORE_ENABLE_CBOR
#define PROTOCORE_ENABLE_CBOR 0
#endif

#ifndef PROTOCORE_ENABLE_MSGPACK
#define PROTOCORE_ENABLE_MSGPACK 0
#endif

// The bounded JSON writer and top-level reader (codec/json).
#ifndef PROTOCORE_ENABLE_JSON
#define PROTOCORE_ENABLE_JSON 0
#endif

// The RFC 1951 sec 3.2.5 length and distance tables, read by the DEFLATE encoder and decoder and by
// the SSH zlib@openssh.com stream codecs.
#ifndef PROTOCORE_ENABLE_DEFLATE_RFC1951
#define PROTOCORE_ENABLE_DEFLATE_RFC1951 0
#endif

// The HTTP route table: the match, the per-route interface gate and the handler a request reaches.
#ifndef PROTOCORE_ENABLE_HTTP_ROUTE
#define PROTOCORE_ENABLE_HTTP_ROUTE 0
#endif

// The built-in dashboard, provisioning form and captive-portal pages served from flash.
#ifndef PROTOCORE_ENABLE_WEB_ASSETS
#define PROTOCORE_ENABLE_WEB_ASSETS 0
#endif

// The DNS query/response codec the resolver and the server both encode through.
#ifndef PROTOCORE_ENABLE_DNS
#define PROTOCORE_ENABLE_DNS 0
#endif

// The TCP surface: the shared connection state every TCP role reaches through.
#ifndef PROTOCORE_ENABLE_TCP
#define PROTOCORE_ENABLE_TCP 0
#endif

// The UDP surface: the shared socket state the client and the listener reach through.
#ifndef PROTOCORE_ENABLE_UDP
#define PROTOCORE_ENABLE_UDP 0
#endif

#ifndef PROTOCORE_ENABLE_FILE_SERVING
#define PROTOCORE_ENABLE_FILE_SERVING 0
#endif

#ifndef PROTOCORE_ENABLE_WEBDAV
#define PROTOCORE_ENABLE_WEBDAV 0
#endif

#ifndef PROTOCORE_ENABLE_AUTH
#define PROTOCORE_ENABLE_AUTH 0
#endif

#ifndef PROTOCORE_ENABLE_TELNET
#define PROTOCORE_ENABLE_TELNET 0
#endif

#ifndef PROTOCORE_ENABLE_SSH
#define PROTOCORE_ENABLE_SSH 0
#endif

#ifndef PROTOCORE_ENABLE_SSH_CLIENT
#define PROTOCORE_ENABLE_SSH_CLIENT 0
#endif

#ifndef PROTOCORE_ENABLE_PQC_KEX
#define PROTOCORE_ENABLE_PQC_KEX 0
#endif

#ifndef PROTOCORE_ENABLE_MODBUS
#define PROTOCORE_ENABLE_MODBUS 0
#endif

#ifndef PROTOCORE_ENABLE_CLOUDEVENTS
#define PROTOCORE_ENABLE_CLOUDEVENTS 0
#endif

#ifndef PROTOCORE_ENABLE_REDIS
#define PROTOCORE_ENABLE_REDIS 0
#endif

#ifndef PROTOCORE_ENABLE_STOMP
#define PROTOCORE_ENABLE_STOMP 0
#endif

#ifndef PROTOCORE_ENABLE_MQTT_SN
#define PROTOCORE_ENABLE_MQTT_SN 0
#endif

#ifndef PROTOCORE_ENABLE_FLOW_EXPORT
#define PROTOCORE_ENABLE_FLOW_EXPORT 0
#endif

#ifndef PROTOCORE_ENABLE_PROTOBUF
#define PROTOCORE_ENABLE_PROTOBUF 0
#endif

#ifndef PROTOCORE_ENABLE_WAMP
#define PROTOCORE_ENABLE_WAMP 0
#endif

#ifndef PROTOCORE_ENABLE_SUNSPEC
#define PROTOCORE_ENABLE_SUNSPEC 0
#endif

#ifndef PROTOCORE_ENABLE_C37118
#define PROTOCORE_ENABLE_C37118 0
#endif

#ifndef PROTOCORE_ENABLE_DNP3
#define PROTOCORE_ENABLE_DNP3 0
#endif

#ifndef PROTOCORE_ENABLE_CANOPEN
#define PROTOCORE_ENABLE_CANOPEN 0
#endif

#ifndef PROTOCORE_ENABLE_CIA402
#define PROTOCORE_ENABLE_CIA402 0
#endif

#ifndef PROTOCORE_ENABLE_CONTROL
#define PROTOCORE_ENABLE_CONTROL 0
#endif

#ifndef PROTOCORE_ENABLE_J1939
#define PROTOCORE_ENABLE_J1939 0
#endif

#ifndef PROTOCORE_ENABLE_DEVICENET
#define PROTOCORE_ENABLE_DEVICENET 0
#endif

#ifndef PROTOCORE_ENABLE_MBUS
#define PROTOCORE_ENABLE_MBUS 0
#endif

#ifndef PROTOCORE_ENABLE_IEC60870
#define PROTOCORE_ENABLE_IEC60870 0
#endif

#ifndef PROTOCORE_ENABLE_SDI12
#define PROTOCORE_ENABLE_SDI12 0
#endif

#ifndef PROTOCORE_ENABLE_DMX
#define PROTOCORE_ENABLE_DMX 0
#endif

#ifndef PROTOCORE_ENABLE_NMEA0183
#define PROTOCORE_ENABLE_NMEA0183 0
#endif

#ifndef PROTOCORE_ENABLE_ROAMING
#define PROTOCORE_ENABLE_ROAMING 0
#endif

#ifndef PROTOCORE_ENABLE_UBX
#define PROTOCORE_ENABLE_UBX 0
#endif

#ifndef PROTOCORE_ENABLE_PTP
#define PROTOCORE_ENABLE_PTP 0
#endif

#ifndef PROTOCORE_ENABLE_IOLINK
#define PROTOCORE_ENABLE_IOLINK 0
#endif

#ifndef PROTOCORE_ENABLE_GRPC_WEB
#define PROTOCORE_ENABLE_GRPC_WEB 0
#endif

#ifndef PROTOCORE_ENABLE_LWM2M
#define PROTOCORE_ENABLE_LWM2M 0
#endif

#ifndef PROTOCORE_ENABLE_FINS
#define PROTOCORE_ENABLE_FINS 0
#endif

#ifndef PROTOCORE_ENABLE_HOSTLINK
#define PROTOCORE_ENABLE_HOSTLINK 0
#endif

#ifndef PROTOCORE_ENABLE_SCPI
#define PROTOCORE_ENABLE_SCPI 0
#endif

#ifndef PROTOCORE_ENABLE_HISLIP
#define PROTOCORE_ENABLE_HISLIP 0
#endif

#ifndef PROTOCORE_ENABLE_VXI11
#define PROTOCORE_ENABLE_VXI11 0
#endif

#ifndef PROTOCORE_ENABLE_GPIB
#define PROTOCORE_ENABLE_GPIB 0
#endif

#ifndef PROTOCORE_ENABLE_HAAS_MDC
#define PROTOCORE_ENABLE_HAAS_MDC 0
#endif

#ifndef PROTOCORE_ENABLE_PACKML
#define PROTOCORE_ENABLE_PACKML 0
#endif

#ifndef PROTOCORE_ENABLE_LSV2
#define PROTOCORE_ENABLE_LSV2 0
#endif

#ifndef PROTOCORE_ENABLE_IKEV2
#define PROTOCORE_ENABLE_IKEV2 0
#endif

#ifndef PROTOCORE_ENABLE_DF1
#define PROTOCORE_ENABLE_DF1 0
#endif

#ifndef PROTOCORE_ENABLE_SIMATIC
#define PROTOCORE_ENABLE_SIMATIC 0
#endif

#ifndef PROTOCORE_ENABLE_COTP
#define PROTOCORE_ENABLE_COTP 0
#endif

#ifndef PROTOCORE_ENABLE_S7COMM
#define PROTOCORE_ENABLE_S7COMM 0
#endif

#ifndef PROTOCORE_ENABLE_MELSEC
#define PROTOCORE_ENABLE_MELSEC 0
#endif

#ifndef PROTOCORE_ENABLE_ADS
#define PROTOCORE_ENABLE_ADS 0
#endif

#ifndef PROTOCORE_ENABLE_FOCAS
#define PROTOCORE_ENABLE_FOCAS 0
#endif

#ifndef PROTOCORE_ENABLE_FANUC_J519
#define PROTOCORE_ENABLE_FANUC_J519 0
#endif

#ifndef PROTOCORE_ENABLE_BACNET
#define PROTOCORE_ENABLE_BACNET 0
#endif

#ifndef PROTOCORE_ENABLE_ENIP
#define PROTOCORE_ENABLE_ENIP 0
#endif

#ifndef PROTOCORE_ENABLE_AMQP
#define PROTOCORE_ENABLE_AMQP 0
#endif

#ifndef PROTOCORE_ENABLE_CIP
#define PROTOCORE_ENABLE_CIP 0
#endif

#ifndef PROTOCORE_ENABLE_NATS
#define PROTOCORE_ENABLE_NATS 0
#endif

#ifndef PROTOCORE_ENABLE_PROXY_PROTOCOL
#define PROTOCORE_ENABLE_PROXY_PROTOCOL 0
#endif

#ifndef PROTOCORE_ENABLE_MODBUS_MASTER
#define PROTOCORE_ENABLE_MODBUS_MASTER 0
#endif

#ifndef PROTOCORE_ENABLE_TLS
#define PROTOCORE_ENABLE_TLS 0
#endif

#ifndef PROTOCORE_ENABLE_TLS_RESUMPTION
#define PROTOCORE_ENABLE_TLS_RESUMPTION 0
#endif

#ifndef PROTOCORE_ENABLE_MTLS
#define PROTOCORE_ENABLE_MTLS 0
#endif

#ifndef PROTOCORE_ENABLE_SNMP
#define PROTOCORE_ENABLE_SNMP 0
#endif

#ifndef PROTOCORE_ENABLE_SNMP_V3
#define PROTOCORE_ENABLE_SNMP_V3 0
#endif

#ifndef PROTOCORE_ENABLE_SNMP_TRAP
#define PROTOCORE_ENABLE_SNMP_TRAP 0
#endif

#ifndef PROTOCORE_ENABLE_COAP
#define PROTOCORE_ENABLE_COAP 0
#endif

#ifndef PROTOCORE_ENABLE_COAP_OBSERVE
#define PROTOCORE_ENABLE_COAP_OBSERVE 0
#endif

#ifndef PROTOCORE_ENABLE_COAP_BLOCK
#define PROTOCORE_ENABLE_COAP_BLOCK 0
#endif

#ifndef PROTOCORE_ENABLE_MDNS
#define PROTOCORE_ENABLE_MDNS 0
#endif

#ifndef PROTOCORE_ENABLE_NTP
#define PROTOCORE_ENABLE_NTP 0
#endif

#ifndef PROTOCORE_ENABLE_NTP_SERVER
#define PROTOCORE_ENABLE_NTP_SERVER 0
#endif

#ifndef PROTOCORE_ENABLE_DNS_SERVER
#define PROTOCORE_ENABLE_DNS_SERVER 0
#endif

#ifndef PROTOCORE_ENABLE_TIME_SOURCE
#define PROTOCORE_ENABLE_TIME_SOURCE 0
#endif

#ifndef PROTOCORE_ENABLE_RTC
#define PROTOCORE_ENABLE_RTC 0
#endif

#ifndef PROTOCORE_ENABLE_LD2410
#define PROTOCORE_ENABLE_LD2410 0
#endif

#ifndef PROTOCORE_ENABLE_RCWL0516
#define PROTOCORE_ENABLE_RCWL0516 0
#endif

#ifndef PROTOCORE_ENABLE_HMMD
#define PROTOCORE_ENABLE_HMMD 0
#endif

#ifndef PROTOCORE_ENABLE_SAFETY_SCL
#define PROTOCORE_ENABLE_SAFETY_SCL 0
#endif

#ifndef PROTOCORE_ENABLE_SEN0192
#define PROTOCORE_ENABLE_SEN0192 0
#endif

#ifndef PROTOCORE_ENABLE_MPR121
#define PROTOCORE_ENABLE_MPR121 0
#endif

#ifndef PROTOCORE_ENABLE_SHT3X
#define PROTOCORE_ENABLE_SHT3X 0
#endif

#ifndef PROTOCORE_ENABLE_PCA9685
#define PROTOCORE_ENABLE_PCA9685 0
#endif

#ifndef PROTOCORE_ENABLE_ADS1115
#define PROTOCORE_ENABLE_ADS1115 0
#endif

#ifndef PROTOCORE_ENABLE_SMBUS
#define PROTOCORE_ENABLE_SMBUS 0
#endif

#ifndef PROTOCORE_ENABLE_PMBUS
#define PROTOCORE_ENABLE_PMBUS 0
#endif

#ifndef PROTOCORE_ENABLE_INA219
#define PROTOCORE_ENABLE_INA219 0
#endif

#ifndef PROTOCORE_ENABLE_CONFIG_STORE
#define PROTOCORE_ENABLE_CONFIG_STORE 0
#endif

#ifndef PROTOCORE_ENABLE_DEVICE_ID
#define PROTOCORE_ENABLE_DEVICE_ID 0
#endif

#ifndef PROTOCORE_ENABLE_TELEMETRY
#define PROTOCORE_ENABLE_TELEMETRY 0
#endif

#ifndef PROTOCORE_ENABLE_DASHBOARD
#define PROTOCORE_ENABLE_DASHBOARD 0
#endif

#ifndef PROTOCORE_ENABLE_THEMES
#define PROTOCORE_ENABLE_THEMES 0
#endif

#ifndef PROTOCORE_ENABLE_PARTITION_MONITOR
#define PROTOCORE_ENABLE_PARTITION_MONITOR 0
#endif

#ifndef PROTOCORE_ENABLE_GPIO_MAP
#define PROTOCORE_ENABLE_GPIO_MAP 0
#endif

#ifndef PROTOCORE_ENABLE_UDP_TELEMETRY
#define PROTOCORE_ENABLE_UDP_TELEMETRY 0
#endif

#ifndef PROTOCORE_ENABLE_STATSD
#define PROTOCORE_ENABLE_STATSD 0
#endif

#ifndef PROTOCORE_ENABLE_GUARDRAILS
#define PROTOCORE_ENABLE_GUARDRAILS 0
#endif

#ifndef PROTOCORE_ENABLE_FAILSAFE
#define PROTOCORE_ENABLE_FAILSAFE 0
#endif

#ifndef PROTOCORE_ENABLE_SLEEP_SCHED
#define PROTOCORE_ENABLE_SLEEP_SCHED 0
#endif

#ifndef PROTOCORE_ENABLE_WEARLEVEL
#define PROTOCORE_ENABLE_WEARLEVEL 0
#endif

#ifndef PROTOCORE_ENABLE_POWER_MGMT
#define PROTOCORE_ENABLE_POWER_MGMT 0
#endif

#ifndef PROTOCORE_ENABLE_HOTSWAP
#define PROTOCORE_ENABLE_HOTSWAP 0
#endif

#ifndef PROTOCORE_ENABLE_NETADAPT
#define PROTOCORE_ENABLE_NETADAPT 0
#endif

#ifndef PROTOCORE_ENABLE_DSHOT
#define PROTOCORE_ENABLE_DSHOT 0
#endif

#ifndef PROTOCORE_ENABLE_HART
#define PROTOCORE_ENABLE_HART 0
#endif

#ifndef PROTOCORE_ENABLE_NTS
#define PROTOCORE_ENABLE_NTS 0
#endif

#ifndef PROTOCORE_ENABLE_DDS
#define PROTOCORE_ENABLE_DDS 0
#endif

#ifndef PROTOCORE_ENABLE_XMPP
#define PROTOCORE_ENABLE_XMPP 0
#endif

#ifndef PROTOCORE_ENABLE_RAWL2
#define PROTOCORE_ENABLE_RAWL2 0
#endif

#ifndef PROTOCORE_ENABLE_SPA_ROUTER
#define PROTOCORE_ENABLE_SPA_ROUTER 0
#endif

#ifndef PROTOCORE_ENABLE_GOOSE
#define PROTOCORE_ENABLE_GOOSE 0
#endif

#ifndef PROTOCORE_ENABLE_MTCONNECT
#define PROTOCORE_ENABLE_MTCONNECT 0
#endif

#ifndef PROTOCORE_ENABLE_WAL
#define PROTOCORE_ENABLE_WAL 0
#endif

#ifndef PROTOCORE_ENABLE_DBM
#define PROTOCORE_ENABLE_DBM 0
#endif

#ifndef PROTOCORE_ENABLE_DOCSTORE
#define PROTOCORE_ENABLE_DOCSTORE 0
#endif

#ifndef PROTOCORE_ENABLE_SQLITE
#define PROTOCORE_ENABLE_SQLITE 0
#endif

#ifndef PROTOCORE_ENABLE_DNC
#define PROTOCORE_ENABLE_DNC 0
#endif

#ifndef PROTOCORE_ENABLE_RELAY
#define PROTOCORE_ENABLE_RELAY 0
#endif

#ifndef PROTOCORE_ENABLE_IFACE_BRIDGE
#define PROTOCORE_ENABLE_IFACE_BRIDGE 0
#endif

#ifndef PROTOCORE_ENABLE_NTRIP_CASTER
#define PROTOCORE_ENABLE_NTRIP_CASTER 0
#endif

#ifndef PROTOCORE_ENABLE_FTP
#define PROTOCORE_ENABLE_FTP 0
#endif

#ifndef PROTOCORE_ENABLE_FTP_SESSION
#define PROTOCORE_ENABLE_FTP_SESSION 0
#endif

#ifndef PROTOCORE_ENABLE_HTTP_CACHE
#define PROTOCORE_ENABLE_HTTP_CACHE 0
#endif

#ifndef PROTOCORE_ENABLE_SMB
#define PROTOCORE_ENABLE_SMB 0
#endif

#ifndef PROTOCORE_ENABLE_J2735
#define PROTOCORE_ENABLE_J2735 0
#endif

#ifndef PROTOCORE_ENABLE_NEMA_TS2
#define PROTOCORE_ENABLE_NEMA_TS2 0
#endif

#ifndef PROTOCORE_ENABLE_SNP
#define PROTOCORE_ENABLE_SNP 0
#endif

#ifndef PROTOCORE_ENABLE_DIRECTNET
#define PROTOCORE_ENABLE_DIRECTNET 0
#endif

#ifndef PROTOCORE_ENABLE_SEP2
#define PROTOCORE_ENABLE_SEP2 0
#endif

#ifndef PROTOCORE_ENABLE_PROFINET
#define PROTOCORE_ENABLE_PROFINET 0
#endif

#ifndef PROTOCORE_ENABLE_NTCIP
#define PROTOCORE_ENABLE_NTCIP 0
#endif

#ifndef PROTOCORE_ENABLE_OPENADR
#define PROTOCORE_ENABLE_OPENADR 0
#endif

#ifndef PROTOCORE_ENABLE_MMS
#define PROTOCORE_ENABLE_MMS 0
#endif

#ifndef PROTOCORE_ENABLE_CCLINK
#define PROTOCORE_ENABLE_CCLINK 0
#endif

#ifndef PROTOCORE_ENABLE_POWERLINK
#define PROTOCORE_ENABLE_POWERLINK 0
#endif

#ifndef PROTOCORE_ENABLE_SERCOS
#define PROTOCORE_ENABLE_SERCOS 0
#endif

#ifndef PROTOCORE_ENABLE_PROFIBUS
#define PROTOCORE_ENABLE_PROFIBUS 0
#endif

#ifndef PROTOCORE_ENABLE_LONWORKS
#define PROTOCORE_ENABLE_LONWORKS 0
#endif

#ifndef PROTOCORE_ENABLE_MBPLUS
#define PROTOCORE_ENABLE_MBPLUS 0
#endif

#ifndef PROTOCORE_ENABLE_INTERBUS
#define PROTOCORE_ENABLE_INTERBUS 0
#endif

#ifndef PROTOCORE_ENABLE_ICCP
#define PROTOCORE_ENABLE_ICCP 0
#endif

#ifndef PROTOCORE_ENABLE_WAVE
#define PROTOCORE_ENABLE_WAVE 0
#endif

#ifndef PROTOCORE_ENABLE_UTMC
#define PROTOCORE_ENABLE_UTMC 0
#endif

#ifndef PROTOCORE_ENABLE_OCIT
#define PROTOCORE_ENABLE_OCIT 0
#endif

#ifndef PROTOCORE_ENABLE_ATC
#define PROTOCORE_ENABLE_ATC 0
#endif

#ifndef PROTOCORE_ENABLE_SOUTHBOUND
#define PROTOCORE_ENABLE_SOUTHBOUND 0
#endif

#ifndef PROTOCORE_ENABLE_EXC_DECODER
#define PROTOCORE_ENABLE_EXC_DECODER 0
#endif

#ifndef PROTOCORE_ENABLE_HTTP_DELIVERY
#define PROTOCORE_ENABLE_HTTP_DELIVERY 0
#endif

#ifndef PROTOCORE_ENABLE_HW_HEALTH
#define PROTOCORE_ENABLE_HW_HEALTH 0
#endif

#ifndef PROTOCORE_ENABLE_MDNS_ADAPTIVE
#define PROTOCORE_ENABLE_MDNS_ADAPTIVE 0
#endif

#ifndef PROTOCORE_ENABLE_SOCKPOOL
#define PROTOCORE_ENABLE_SOCKPOOL 0
#endif

#ifndef PROTOCORE_ENABLE_PSRAM_POOL
#define PROTOCORE_ENABLE_PSRAM_POOL 0
#endif

#ifndef PROTOCORE_ENABLE_HAPPY_EYEBALLS
#define PROTOCORE_ENABLE_HAPPY_EYEBALLS 0
#endif

#ifndef PROTOCORE_ENABLE_WIFI_SNIFFER
#define PROTOCORE_ENABLE_WIFI_SNIFFER 0
#endif

#ifndef PROTOCORE_ENABLE_LINK_MANAGER
#define PROTOCORE_ENABLE_LINK_MANAGER 0
#endif

#ifndef PROTOCORE_ENABLE_CC1101
#define PROTOCORE_ENABLE_CC1101 0
#endif

#ifndef PROTOCORE_ENABLE_FDC2214
#define PROTOCORE_ENABLE_FDC2214 0
#endif

#ifndef PROTOCORE_ENABLE_LDC1614
#define PROTOCORE_ENABLE_LDC1614 0
#endif

#ifndef PROTOCORE_ENABLE_VL53L0X
#define PROTOCORE_ENABLE_VL53L0X 0
#endif

#ifndef PROTOCORE_ENABLE_RADIO_SNIFF
#define PROTOCORE_ENABLE_RADIO_SNIFF 0
#endif

#ifndef PROTOCORE_ENABLE_BLE_GATT
#define PROTOCORE_ENABLE_BLE_GATT 0
#endif

#ifndef PROTOCORE_ENABLE_TLS_POLICY
#define PROTOCORE_ENABLE_TLS_POLICY 0
#endif

#ifndef PROTOCORE_ENABLE_WISUN
#define PROTOCORE_ENABLE_WISUN 0
#endif

#ifndef PROTOCORE_ENABLE_LOGBUF
#define PROTOCORE_ENABLE_LOGBUF 0
#endif

#ifndef PROTOCORE_ENABLE_CONFIG_IO
#define PROTOCORE_ENABLE_CONFIG_IO 0
#endif

#ifndef PROTOCORE_ENABLE_OTA
#define PROTOCORE_ENABLE_OTA 0
#endif

#ifndef PROTOCORE_ENABLE_OTA_ROLLBACK
#define PROTOCORE_ENABLE_OTA_ROLLBACK 0
#endif

#ifndef PROTOCORE_ENABLE_TOTP
#define PROTOCORE_ENABLE_TOTP 0
#endif

#ifndef PROTOCORE_ENABLE_WEBHOOK
#define PROTOCORE_ENABLE_WEBHOOK 0
#endif

#ifndef PROTOCORE_ENABLE_RADIO_POWER
#define PROTOCORE_ENABLE_RADIO_POWER 0
#endif

#ifndef PROTOCORE_ENABLE_DNS_RESOLVER
#define PROTOCORE_ENABLE_DNS_RESOLVER 0
#endif

#ifndef PROTOCORE_ENABLE_AUDIT_LOG
#define PROTOCORE_ENABLE_AUDIT_LOG 0
#endif

#ifndef PROTOCORE_ENABLE_OIDC
#define PROTOCORE_ENABLE_OIDC 0
#endif

#ifndef PROTOCORE_ENABLE_MNT
#define PROTOCORE_ENABLE_MNT 0
#endif

#ifndef PROTOCORE_ENABLE_GRAPHQL
#define PROTOCORE_ENABLE_GRAPHQL 0
#endif

#ifndef PROTOCORE_ENABLE_ESPNOW
#define PROTOCORE_ENABLE_ESPNOW 0
#endif

#ifndef PROTOCORE_ENABLE_OAUTH2
#define PROTOCORE_ENABLE_OAUTH2 0
#endif

#ifndef PROTOCORE_ENABLE_OPCUA
#define PROTOCORE_ENABLE_OPCUA 0
#endif

#ifndef PROTOCORE_ENABLE_OPCUA_CLIENT
#define PROTOCORE_ENABLE_OPCUA_CLIENT 0
#endif

#ifndef PROTOCORE_ENABLE_UMATI
#define PROTOCORE_ENABLE_UMATI 0
#endif

#ifndef PROTOCORE_ENABLE_ROBOTICS
#define PROTOCORE_ENABLE_ROBOTICS 0
#endif

#ifndef PROTOCORE_ENABLE_EUROMAP77
#define PROTOCORE_ENABLE_EUROMAP77 0
#endif

#ifndef PROTOCORE_ENABLE_UPLOAD
#define PROTOCORE_ENABLE_UPLOAD 0
#endif

#ifndef PROTOCORE_ENABLE_PROVISIONING
#define PROTOCORE_ENABLE_PROVISIONING 0
#endif

#ifndef PROTOCORE_ENABLE_SYSLOG
#define PROTOCORE_ENABLE_SYSLOG 0
#endif

#ifndef PROTOCORE_ENABLE_JWT
#define PROTOCORE_ENABLE_JWT 0
#endif

#ifndef PROTOCORE_ENABLE_HTTP_CLIENT
#define PROTOCORE_ENABLE_HTTP_CLIENT 0
#endif

#ifndef PROTOCORE_ENABLE_HTTP_CLIENT_TLS
#define PROTOCORE_ENABLE_HTTP_CLIENT_TLS 0
#endif

#ifndef PROTOCORE_ENABLE_SMTP
#define PROTOCORE_ENABLE_SMTP 0
#endif

#ifndef PROTOCORE_ENABLE_SMTP_TLS
#define PROTOCORE_ENABLE_SMTP_TLS 0
#endif

#ifndef PROTOCORE_ENABLE_MQTT
#define PROTOCORE_ENABLE_MQTT 0
#endif

#ifndef PROTOCORE_ENABLE_MQTT_TLS
#define PROTOCORE_ENABLE_MQTT_TLS 0
#endif

#ifndef PROTOCORE_ENABLE_WS_CLIENT
#define PROTOCORE_ENABLE_WS_CLIENT 0
#endif

#ifndef PROTOCORE_ENABLE_WS_CLIENT_TLS
#define PROTOCORE_ENABLE_WS_CLIENT_TLS 0
#endif

#ifndef PROTOCORE_ENABLE_STATS
#define PROTOCORE_ENABLE_STATS 0
#endif

#ifndef PROTOCORE_ENABLE_OBSERVABILITY
#define PROTOCORE_ENABLE_OBSERVABILITY 0
#endif

#ifndef PROTOCORE_ENABLE_METRICS
#define PROTOCORE_ENABLE_METRICS 0
#endif

#ifndef PROTOCORE_ENABLE_WEB_TERMINAL
#define PROTOCORE_ENABLE_WEB_TERMINAL 0
#endif

#ifndef PROTOCORE_ENABLE_ETAG
#define PROTOCORE_ENABLE_ETAG 0
#endif

#ifndef PROTOCORE_ENABLE_DIAG
#define PROTOCORE_ENABLE_DIAG 0
#endif

#ifndef PROTOCORE_ENABLE_KEEPALIVE
#define PROTOCORE_ENABLE_KEEPALIVE 0
#endif

#ifndef PROTOCORE_ENABLE_HTTP2
#define PROTOCORE_ENABLE_HTTP2 0
#endif

#ifndef PROTOCORE_ENABLE_HTTP3
#define PROTOCORE_ENABLE_HTTP3 0
#endif

#ifndef PROTOCORE_ENABLE_DTLS
#define PROTOCORE_ENABLE_DTLS 0
#endif

#ifndef PROTOCORE_ENABLE_TLS_RPK
#define PROTOCORE_ENABLE_TLS_RPK 0
#endif

#ifndef PROTOCORE_ENABLE_X509
#define PROTOCORE_ENABLE_X509 0
#endif

#ifndef PROTOCORE_ENABLE_RANGE
#define PROTOCORE_ENABLE_RANGE 0
#endif

#ifndef PROTOCORE_ENABLE_SSH_KEYBOARD_INTERACTIVE
#define PROTOCORE_ENABLE_SSH_KEYBOARD_INTERACTIVE 0
#endif

#ifndef PROTOCORE_ENABLE_ACCEPT_THROTTLE
#define PROTOCORE_ENABLE_ACCEPT_THROTTLE 0
#endif

#ifndef PROTOCORE_ENABLE_PER_IP_THROTTLE
#define PROTOCORE_ENABLE_PER_IP_THROTTLE 0
#endif

#ifndef PROTOCORE_ENABLE_IP_ALLOWLIST
#define PROTOCORE_ENABLE_IP_ALLOWLIST 0
#endif

#ifndef PROTOCORE_ENABLE_FORWARDED_TRUST
#define PROTOCORE_ENABLE_FORWARDED_TRUST 0
#endif

#ifndef PROTOCORE_ENABLE_AUTH_LOCKOUT
#define PROTOCORE_ENABLE_AUTH_LOCKOUT 0
#endif

#ifndef PROTOCORE_ENABLE_CSRF
#define PROTOCORE_ENABLE_CSRF 0
#endif

#ifndef PROTOCORE_ENABLE_SSH_SFTP
#define PROTOCORE_ENABLE_SSH_SFTP 0
#endif

#ifndef PROTOCORE_ENABLE_SSH_SCP
#define PROTOCORE_ENABLE_SSH_SCP 0
#endif

#ifndef PROTOCORE_ENABLE_SSH_ZLIB
#define PROTOCORE_ENABLE_SSH_ZLIB 0
#endif

// Ungated before the wrap, so they stand where they stood.
#ifndef PROTOCORE_ENABLE_SHA1
#define PROTOCORE_ENABLE_SHA1 1
#endif
#ifndef PROTOCORE_ENABLE_SHA256
#define PROTOCORE_ENABLE_SHA256 1
#endif
#ifndef PROTOCORE_ENABLE_SHA512
#define PROTOCORE_ENABLE_SHA512 1
#endif
#ifndef PROTOCORE_ENABLE_MD
#define PROTOCORE_ENABLE_MD 1
#endif
#ifndef PROTOCORE_ENABLE_HMAC_SHA256
#define PROTOCORE_ENABLE_HMAC_SHA256 1
#endif
#ifndef PROTOCORE_ENABLE_HMAC_SHA512
#define PROTOCORE_ENABLE_HMAC_SHA512 1
#endif
#ifndef PROTOCORE_ENABLE_POLY1305
#define PROTOCORE_ENABLE_POLY1305 1
#endif
#ifndef PROTOCORE_ENABLE_AES_CMAC
#define PROTOCORE_ENABLE_AES_CMAC 1
#endif
#ifndef PROTOCORE_ENABLE_GHASH
#define PROTOCORE_ENABLE_GHASH 1
#endif
// The constant-time compare. Every tag check in the library ends at it and mmgr/protomem.h and
// mmgr/protostr.h both reach for it, so a build that turns this off has no AEAD open and no
// authenticated anything: it is stated for the shape every other primitive has, not as a knob.
#ifndef PROTOCORE_ENABLE_CT_EQ
#define PROTOCORE_ENABLE_CT_EQ 1
#endif
// The raw byte mover, under every span copy and every unaligned fill in the tree. Stated for the
// shape every other module has rather than as a knob: mmgr is the substrate a borrow is carved out
// of, so a build that turns this off has no memory manager and links nothing.
#ifndef PROTOCORE_ENABLE_RAWMEMCPY
#define PROTOCORE_ENABLE_RAWMEMCPY 1
#endif
// The request parser. Every HTTP path in the library feeds it, and 53 envs build it with no flag in
// common, so a build that turns this off serves nothing over HTTP: stated for the shape every other
// module has, not as a knob.
#ifndef PROTOCORE_ENABLE_HTTP_PARSER
#define PROTOCORE_ENABLE_HTTP_PARSER 1
#endif
// The RSA host key: DER parsing, the ssh-rsa blob encoding, and signing through Rsa. Named for SSH
// but reached by IKEv2 and OIDC too, and 17 envs build it with no flag in common, so it is stated
// for the shape every other module has rather than gated on any one caller.
#ifndef PROTOCORE_ENABLE_SSH_RSA
#define PROTOCORE_ENABLE_SSH_RSA 1
#endif
// The base64 codec. The WebSocket accept digest, Basic auth, JWS and every PEM path reach it, and 52
// envs build it with no flag in common: stated for the shape every other module has, not as a knob.
#ifndef PROTOCORE_ENABLE_BASE64
#define PROTOCORE_ENABLE_BASE64 1
#endif
#ifndef PROTOCORE_ENABLE_KDF
#define PROTOCORE_ENABLE_KDF 1
#endif
#ifndef PROTOCORE_ENABLE_AESGCM
#define PROTOCORE_ENABLE_AESGCM 1
#endif
#ifndef PROTOCORE_ENABLE_CHACHAPOLY
#define PROTOCORE_ENABLE_CHACHAPOLY 1
#endif
#ifndef PROTOCORE_ENABLE_CHACHA20
#define PROTOCORE_ENABLE_CHACHA20 1
#endif
#ifndef PROTOCORE_ENABLE_AES256CTR
#define PROTOCORE_ENABLE_AES256CTR 1
#endif
#ifndef PROTOCORE_ENABLE_AES_BLOCK
#define PROTOCORE_ENABLE_AES_BLOCK 1
#endif
#ifndef PROTOCORE_ENABLE_AES_SBOX
#define PROTOCORE_ENABLE_AES_SBOX 1
#endif
#ifndef PROTOCORE_ENABLE_BIGNUM
#define PROTOCORE_ENABLE_BIGNUM 1
#endif
#ifndef PROTOCORE_ENABLE_CURVE25519
#define PROTOCORE_ENABLE_CURVE25519 1
#endif
#ifndef PROTOCORE_ENABLE_FE25519
#define PROTOCORE_ENABLE_FE25519 1
#endif
#ifndef PROTOCORE_ENABLE_ECDSA
#define PROTOCORE_ENABLE_ECDSA 1
#endif
#ifndef PROTOCORE_ENABLE_ED25519
#define PROTOCORE_ENABLE_ED25519 1
#endif
#ifndef PROTOCORE_ENABLE_RSA
#define PROTOCORE_ENABLE_RSA 1
#endif
#ifndef PROTOCORE_ENABLE_RNG
#define PROTOCORE_ENABLE_RNG 1
#endif

// The flags these decide: a value read off another flag, or one an enabled feature forces on.
#include "config/features/feature_dependency_en.h"

// Everything the flags above are spent on: capacities, buffer extents and pool borrows.
#include "config/memory_sizing/buffer_sizing.h"

// What those flags require of each other and of the sizing.
#include "config/features/feature_en_error.h"

// Final sizing pass: raise buffers to the floors the enabled features require (every PROTOCORE_ENABLE_*
// flag is resolved by this point).
#include "derived_sizing.h" // PROTOCORE_ALLOW_LATE_INCLUDE: ordered - reads the flags resolved above

#endif
