# ProtoCore v1.0.16 - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Every feature flag, declared once, here.
#
# A module is gated by NOT BEING BUILT - protocore_add_module() returns early when its GATE is
# off - rather than by compiling to an empty translation unit. The option is also passed to the
# compiler, because a flag decides more than whether a module exists: it selects arms inside
# modules that are built either way, and the Arduino shim has no source selection at all and
# reaches these only as -D flags out of its build_opt.h.
#
# GENERATED ONCE from the config headers' own defaults, then maintained here.

# Hardware capabilities a module's gate can name. OFF by default: the host has none of
# them, and a part that does states it. Declared so a compound gate resolves from a real
# option rather than from a variable that happens to be undefined.
option(PROTOCORE_HAS_VENDOR_COREDUMP "" OFF)
option(PROTOCORE_HAS_VENDOR_OTA "" OFF)

option(PROTOCORE_ENABLE_ACCEPT_THROTTLE "" OFF)
option(PROTOCORE_ENABLE_AD9238 "" OFF)
option(PROTOCORE_ENABLE_ADS "" OFF)
option(PROTOCORE_ENABLE_ADS1115 "" OFF)
option(PROTOCORE_ENABLE_AES256CTR "" ON)
option(PROTOCORE_ENABLE_AESGCM "" ON)
option(PROTOCORE_ENABLE_AES_BLOCK "" ON)
option(PROTOCORE_ENABLE_AES_CMAC "" ON)
option(PROTOCORE_ENABLE_AES_SBOX "" ON)
option(PROTOCORE_ENABLE_AMQP "" OFF)
option(PROTOCORE_ENABLE_ATC "" OFF)
option(PROTOCORE_ENABLE_AUDIT_LOG "" OFF)
option(PROTOCORE_ENABLE_AUTH "" OFF)
option(PROTOCORE_ENABLE_AUTH_LOCKOUT "" OFF)
option(PROTOCORE_ENABLE_BACNET "" OFF)
option(PROTOCORE_ENABLE_BASE64 "" ON)
option(PROTOCORE_ENABLE_BIGNUM "" ON)
option(PROTOCORE_ENABLE_BLE_GATT "" OFF)
option(PROTOCORE_ENABLE_BUS_CAPTURE "" OFF)
option(PROTOCORE_ENABLE_C37118 "" OFF)
option(PROTOCORE_ENABLE_CANOPEN "" OFF)
option(PROTOCORE_ENABLE_CBOR "" OFF)
option(PROTOCORE_ENABLE_CC1101 "" OFF)
option(PROTOCORE_ENABLE_CCLINK "" OFF)
option(PROTOCORE_ENABLE_CHACHA20 "" ON)
option(PROTOCORE_ENABLE_CHACHAPOLY "" ON)
option(PROTOCORE_ENABLE_CIA402 "" OFF)
option(PROTOCORE_ENABLE_CIP "" OFF)
option(PROTOCORE_ENABLE_CLOUDEVENTS "" OFF)
option(PROTOCORE_ENABLE_COAP "" OFF)
option(PROTOCORE_ENABLE_COAP_BLOCK "" OFF)
option(PROTOCORE_ENABLE_COAP_OBSERVE "" OFF)
option(PROTOCORE_ENABLE_CONFIG_IO "" OFF)
option(PROTOCORE_ENABLE_CONFIG_STORE "" OFF)
option(PROTOCORE_ENABLE_CONTROL "" OFF)
option(PROTOCORE_ENABLE_COTP "" OFF)
option(PROTOCORE_ENABLE_CSRF "" OFF)
option(PROTOCORE_ENABLE_CT_EQ "" ON)
option(PROTOCORE_ENABLE_CURVE25519 "" ON)
option(PROTOCORE_ENABLE_DASHBOARD "" OFF)
option(PROTOCORE_ENABLE_DBM "" OFF)
option(PROTOCORE_ENABLE_DDS "" OFF)
option(PROTOCORE_ENABLE_DEFLATE_RFC1951 "" OFF)
option(PROTOCORE_ENABLE_DEVICENET "" OFF)
option(PROTOCORE_ENABLE_DEVICE_ID "" OFF)
option(PROTOCORE_ENABLE_DF1 "" OFF)
option(PROTOCORE_ENABLE_DIAG "" OFF)
option(PROTOCORE_ENABLE_DIFFSERV "" OFF)
option(PROTOCORE_ENABLE_DIRECTNET "" OFF)
option(PROTOCORE_ENABLE_DMA "" OFF)
option(PROTOCORE_ENABLE_DMX "" OFF)
option(PROTOCORE_ENABLE_DNC "" OFF)
option(PROTOCORE_ENABLE_DNP3 "" OFF)
option(PROTOCORE_ENABLE_DNS "" OFF)
option(PROTOCORE_ENABLE_DNS_RESOLVER "" OFF)
option(PROTOCORE_ENABLE_DNS_SERVER "" OFF)
option(PROTOCORE_ENABLE_DOCSTORE "" OFF)
option(PROTOCORE_ENABLE_DSHOT "" OFF)
option(PROTOCORE_ENABLE_DTLS "" OFF)
option(PROTOCORE_ENABLE_ECDSA "" ON)
option(PROTOCORE_ENABLE_ED25519 "" ON)
option(PROTOCORE_ENABLE_EDGE_CACHE "" OFF)
option(PROTOCORE_ENABLE_EDGE_MESH "" OFF)
option(PROTOCORE_ENABLE_ENIP "" OFF)
option(PROTOCORE_ENABLE_ENOCEAN "" OFF)
option(PROTOCORE_ENABLE_ESPNOW "" OFF)
option(PROTOCORE_ENABLE_ETAG "" OFF)
option(PROTOCORE_ENABLE_ETHERNET "" OFF)
option(PROTOCORE_ENABLE_EUROMAP77 "" OFF)
option(PROTOCORE_ENABLE_EXC_DECODER "" OFF)
option(PROTOCORE_ENABLE_FAILSAFE "" OFF)
option(PROTOCORE_ENABLE_FANUC_J519 "" OFF)
option(PROTOCORE_ENABLE_FDC2214 "" OFF)
option(PROTOCORE_ENABLE_FE25519 "" ON)
option(PROTOCORE_ENABLE_FILE_SERVING "" OFF)
option(PROTOCORE_ENABLE_FINS "" OFF)
option(PROTOCORE_ENABLE_FLOW_EXPORT "" OFF)
option(PROTOCORE_ENABLE_FOCAS "" OFF)
option(PROTOCORE_ENABLE_FORWARD "" OFF)
option(PROTOCORE_ENABLE_FORWARDED_TRUST "" OFF)
option(PROTOCORE_ENABLE_FTP "" OFF)
option(PROTOCORE_ENABLE_FTP_SESSION "" OFF)
option(PROTOCORE_ENABLE_GATEWAY "" OFF)
option(PROTOCORE_ENABLE_GHASH "" ON)
option(PROTOCORE_ENABLE_GOOSE "" OFF)
option(PROTOCORE_ENABLE_GPIB "" OFF)
option(PROTOCORE_ENABLE_GPIO_MAP "" OFF)
option(PROTOCORE_ENABLE_GRAPHQL "" OFF)
option(PROTOCORE_ENABLE_GRPC_WEB "" OFF)
option(PROTOCORE_ENABLE_GUARDRAILS "" OFF)
option(PROTOCORE_ENABLE_HAAS_MDC "" OFF)
option(PROTOCORE_ENABLE_HAPPY_EYEBALLS "" OFF)
option(PROTOCORE_ENABLE_HART "" OFF)
option(PROTOCORE_ENABLE_HISLIP "" OFF)
option(PROTOCORE_ENABLE_HMAC_SHA256 "" ON)
option(PROTOCORE_ENABLE_HMAC_SHA512 "" ON)
option(PROTOCORE_ENABLE_HMMD "" OFF)
option(PROTOCORE_ENABLE_HOSTLINK "" OFF)
option(PROTOCORE_ENABLE_HOTSWAP "" OFF)
option(PROTOCORE_ENABLE_HTTP2 "" OFF)
option(PROTOCORE_ENABLE_HTTP3 "" OFF)
option(PROTOCORE_ENABLE_HTTP_CACHE "" OFF)
option(PROTOCORE_ENABLE_HTTP_CLIENT "" OFF)
option(PROTOCORE_ENABLE_HTTP_CLOCK "" OFF)
option(PROTOCORE_ENABLE_HTTP_DELIVERY "" OFF)
option(PROTOCORE_ENABLE_HTTP_PARSER "" ON)
option(PROTOCORE_ENABLE_HTTP_ROUTE "" OFF)
option(PROTOCORE_ENABLE_HW_HEALTH "" OFF)
option(PROTOCORE_ENABLE_ICCP "" OFF)
option(PROTOCORE_ENABLE_IEC60870 "" OFF)
option(PROTOCORE_ENABLE_IFACE_BRIDGE "" OFF)
option(PROTOCORE_ENABLE_IKEV2 "" OFF)
option(PROTOCORE_ENABLE_INA219 "" OFF)
option(PROTOCORE_ENABLE_INTERBUS "" OFF)
option(PROTOCORE_ENABLE_IOLINK "" OFF)
option(PROTOCORE_ENABLE_IPV6 "" OFF)
option(PROTOCORE_ENABLE_IP_ALLOWLIST "" OFF)
option(PROTOCORE_ENABLE_J1939 "" OFF)
option(PROTOCORE_ENABLE_J2735 "" OFF)
option(PROTOCORE_ENABLE_JSON "" OFF)
option(PROTOCORE_ENABLE_JWT "" OFF)
option(PROTOCORE_ENABLE_KDF "" ON)
option(PROTOCORE_ENABLE_KEEPALIVE "" OFF)
option(PROTOCORE_ENABLE_LD2410 "" OFF)
option(PROTOCORE_ENABLE_LDC1614 "" OFF)
option(PROTOCORE_ENABLE_LINK_MANAGER "" OFF)
option(PROTOCORE_ENABLE_LOGBUF "" OFF)
option(PROTOCORE_ENABLE_LONWORKS "" OFF)
option(PROTOCORE_ENABLE_LORA "" OFF)
option(PROTOCORE_ENABLE_LSV2 "" OFF)
option(PROTOCORE_ENABLE_LWM2M "" OFF)
option(PROTOCORE_ENABLE_MBPLUS "" OFF)
option(PROTOCORE_ENABLE_MBUS "" OFF)
option(PROTOCORE_ENABLE_MD "" ON)
option(PROTOCORE_ENABLE_MDNS "" OFF)
option(PROTOCORE_ENABLE_MDNS_ADAPTIVE "" OFF)
option(PROTOCORE_ENABLE_MELSEC "" OFF)
option(PROTOCORE_ENABLE_METRICS "" OFF)
option(PROTOCORE_ENABLE_MMS "" OFF)
option(PROTOCORE_ENABLE_MNT "" OFF)
option(PROTOCORE_ENABLE_MODBUS "" OFF)
option(PROTOCORE_ENABLE_MODBUS_MASTER "" OFF)
option(PROTOCORE_ENABLE_MODBUS_RTU "" OFF)
option(PROTOCORE_ENABLE_MPR121 "" OFF)
option(PROTOCORE_ENABLE_MQTT "" OFF)
option(PROTOCORE_ENABLE_MQTT_SN "" OFF)
option(PROTOCORE_ENABLE_MSGPACK "" OFF)
option(PROTOCORE_ENABLE_MTCONNECT "" OFF)
option(PROTOCORE_ENABLE_MULTIPART "" OFF)
option(PROTOCORE_ENABLE_NATS "" OFF)
option(PROTOCORE_ENABLE_NEMA_TS2 "" OFF)
option(PROTOCORE_ENABLE_NETADAPT "" OFF)
option(PROTOCORE_ENABLE_NMEA0183 "" OFF)
option(PROTOCORE_ENABLE_NMEA2000 "" OFF)
option(PROTOCORE_ENABLE_NRF24 "" OFF)
option(PROTOCORE_ENABLE_NTCIP "" OFF)
option(PROTOCORE_ENABLE_NTP "" OFF)
option(PROTOCORE_ENABLE_NTP_SERVER "" OFF)
option(PROTOCORE_ENABLE_NTRIP_CASTER "" OFF)
option(PROTOCORE_ENABLE_NTS "" OFF)
option(PROTOCORE_ENABLE_OAUTH2 "" OFF)
option(PROTOCORE_ENABLE_OBSERVABILITY "" OFF)
option(PROTOCORE_ENABLE_OCIT "" OFF)
option(PROTOCORE_ENABLE_OIDC "" OFF)
option(PROTOCORE_ENABLE_OPCUA "" OFF)
option(PROTOCORE_ENABLE_OPCUA_CLIENT "" OFF)
option(PROTOCORE_ENABLE_OPENADR "" OFF)
option(PROTOCORE_ENABLE_OTA "" OFF)
option(PROTOCORE_ENABLE_OTA_ROLLBACK "" OFF)
option(PROTOCORE_ENABLE_PACKML "" OFF)
option(PROTOCORE_ENABLE_PARTITION_MONITOR "" OFF)
option(PROTOCORE_ENABLE_PCA9685 "" OFF)
option(PROTOCORE_ENABLE_PER_IP_THROTTLE "" OFF)
option(PROTOCORE_ENABLE_PMBUS "" OFF)
option(PROTOCORE_ENABLE_PN532 "" OFF)
option(PROTOCORE_ENABLE_POLY1305 "" ON)
option(PROTOCORE_ENABLE_POWERLINK "" OFF)
option(PROTOCORE_ENABLE_POWER_MGMT "" OFF)
option(PROTOCORE_ENABLE_PQC_KEX "" OFF)
option(PROTOCORE_ENABLE_PREEMPT_QUEUE "" OFF)
option(PROTOCORE_ENABLE_PROFIBUS "" OFF)
option(PROTOCORE_ENABLE_PROFINET "" OFF)
option(PROTOCORE_ENABLE_PROMISC "" OFF)
option(PROTOCORE_ENABLE_PROTOBUF "" OFF)
option(PROTOCORE_ENABLE_PROVISIONING "" OFF)
option(PROTOCORE_ENABLE_PROXY_PROTOCOL "" OFF)
option(PROTOCORE_ENABLE_PSRAM_POOL "" OFF)
option(PROTOCORE_ENABLE_PTP "" OFF)
option(PROTOCORE_ENABLE_RADIO_POWER "" OFF)
option(PROTOCORE_ENABLE_RADIO_SNIFF "" OFF)
option(PROTOCORE_ENABLE_RANGE "" OFF)
option(PROTOCORE_ENABLE_RAWL2 "" OFF)
option(PROTOCORE_ENABLE_RAWMEMCPY "" ON)
option(PROTOCORE_ENABLE_RCWL0516 "" OFF)
option(PROTOCORE_ENABLE_REDIS "" OFF)
option(PROTOCORE_ENABLE_RELAY "" OFF)
option(PROTOCORE_ENABLE_RNG "" ON)
option(PROTOCORE_ENABLE_ROAMING "" OFF)
option(PROTOCORE_ENABLE_ROBOTICS "" OFF)
option(PROTOCORE_ENABLE_RSA "" ON)
option(PROTOCORE_ENABLE_RTC "" OFF)
option(PROTOCORE_ENABLE_S7COMM "" OFF)
option(PROTOCORE_ENABLE_SAFETY_SCL "" OFF)
option(PROTOCORE_ENABLE_SCPI "" OFF)
option(PROTOCORE_ENABLE_SDI12 "" OFF)
option(PROTOCORE_ENABLE_SEN0192 "" OFF)
option(PROTOCORE_ENABLE_SENML "" OFF)
option(PROTOCORE_ENABLE_SEP2 "" OFF)
option(PROTOCORE_ENABLE_SERCOS "" OFF)
option(PROTOCORE_ENABLE_SHA1 "" ON)
option(PROTOCORE_ENABLE_SHA256 "" ON)
option(PROTOCORE_ENABLE_SHA512 "" ON)
option(PROTOCORE_ENABLE_SHT3X "" OFF)
option(PROTOCORE_ENABLE_SIGFOX "" OFF)
option(PROTOCORE_ENABLE_SIMATIC "" OFF)
option(PROTOCORE_ENABLE_SLEEP_SCHED "" OFF)
option(PROTOCORE_ENABLE_SMB "" OFF)
option(PROTOCORE_ENABLE_SMBUS "" OFF)
option(PROTOCORE_ENABLE_SMTP "" OFF)
option(PROTOCORE_ENABLE_SNMP "" OFF)
option(PROTOCORE_ENABLE_SNMP_TRAP "" OFF)
option(PROTOCORE_ENABLE_SNMP_V3 "" OFF)
option(PROTOCORE_ENABLE_SNP "" OFF)
option(PROTOCORE_ENABLE_SOCKPOOL "" OFF)
option(PROTOCORE_ENABLE_SOUTHBOUND "" OFF)
option(PROTOCORE_ENABLE_SPARKPLUG "" OFF)
option(PROTOCORE_ENABLE_SPA_ROUTER "" OFF)
option(PROTOCORE_ENABLE_SQLITE "" OFF)
option(PROTOCORE_ENABLE_SSE "" OFF)
option(PROTOCORE_ENABLE_SSH "" OFF)
option(PROTOCORE_ENABLE_SSH_CLIENT "" OFF)
option(PROTOCORE_ENABLE_SSH_KEYBOARD_INTERACTIVE "" OFF)
option(PROTOCORE_ENABLE_SSH_RSA "" ON)
option(PROTOCORE_ENABLE_SSH_SCP "" OFF)
option(PROTOCORE_ENABLE_SSH_SFTP "" OFF)
option(PROTOCORE_ENABLE_SSH_ZLIB "" OFF)
option(PROTOCORE_ENABLE_STATS "" OFF)
option(PROTOCORE_ENABLE_STATSD "" OFF)
option(PROTOCORE_ENABLE_STOMP "" OFF)
option(PROTOCORE_ENABLE_SUNSPEC "" OFF)
option(PROTOCORE_ENABLE_SYSLOG "" OFF)
option(PROTOCORE_ENABLE_TCP "" OFF)
option(PROTOCORE_ENABLE_TCP_CLIENT "" OFF)
option(PROTOCORE_ENABLE_TELEMETRY "" OFF)
option(PROTOCORE_ENABLE_TELNET "" OFF)
option(PROTOCORE_ENABLE_THEMES "" OFF)
option(PROTOCORE_ENABLE_THREAD "" OFF)
option(PROTOCORE_ENABLE_TIME_SOURCE "" OFF)
option(PROTOCORE_ENABLE_TLS "" OFF)
option(PROTOCORE_ENABLE_TLS_POLICY "" OFF)
option(PROTOCORE_ENABLE_TLS_RESUMPTION "" OFF)
option(PROTOCORE_ENABLE_TLS_RPK "" OFF)
option(PROTOCORE_ENABLE_TOTP "" OFF)
option(PROTOCORE_ENABLE_TRACE_CAPTURE "" OFF)
option(PROTOCORE_ENABLE_UBX "" OFF)
option(PROTOCORE_ENABLE_UDP "" OFF)
option(PROTOCORE_ENABLE_UDP_TELEMETRY "" OFF)
option(PROTOCORE_ENABLE_UMATI "" OFF)
option(PROTOCORE_ENABLE_UPLOAD "" OFF)
option(PROTOCORE_ENABLE_UTMC "" OFF)
option(PROTOCORE_ENABLE_VL53L0X "" OFF)
option(PROTOCORE_ENABLE_VXI11 "" OFF)
option(PROTOCORE_ENABLE_WAL "" OFF)
option(PROTOCORE_ENABLE_WAMP "" OFF)
option(PROTOCORE_ENABLE_WAVE "" OFF)
option(PROTOCORE_ENABLE_WEARLEVEL "" OFF)
option(PROTOCORE_ENABLE_WEBDAV "" OFF)
option(PROTOCORE_ENABLE_WEBHOOK "" OFF)
option(PROTOCORE_ENABLE_WEBSOCKET "" OFF)
option(PROTOCORE_ENABLE_WEB_ASSETS "" OFF)
option(PROTOCORE_ENABLE_WEB_TERMINAL "" OFF)
option(PROTOCORE_ENABLE_WIFI_SNIFFER "" OFF)
option(PROTOCORE_ENABLE_WISUN "" OFF)
option(PROTOCORE_ENABLE_WS_CLIENT "" OFF)
option(PROTOCORE_ENABLE_WS_DEFLATE "" OFF)
option(PROTOCORE_ENABLE_X509 "" OFF)
option(PROTOCORE_ENABLE_XMPP "" OFF)
option(PROTOCORE_ENABLE_ZIGBEE "" OFF)
option(PROTOCORE_ENABLE_ZWAVE "" OFF)

# What a feature needs. These were `#error` rules in feature_dependency_en.h; a build that
# asks for a feature without what it rests on now fails at CONFIGURE, naming both, instead of
# part way through a compile.
function(protocore_requires child parent)
  if(${child} AND NOT ${parent})
    message(FATAL_ERROR "${child} needs ${parent}")
  endif()
endfunction()

protocore_requires(PROTOCORE_ENABLE_MODBUS_RTU PROTOCORE_ENABLE_MODBUS)
protocore_requires(PROTOCORE_ENABLE_NMEA2000 PROTOCORE_ENABLE_J1939)
protocore_requires(PROTOCORE_ENABLE_SENML PROTOCORE_ENABLE_CBOR)
protocore_requires(PROTOCORE_ENABLE_SPARKPLUG PROTOCORE_ENABLE_PROTOBUF)
protocore_requires(PROTOCORE_ENABLE_NTP_SERVER PROTOCORE_ENABLE_TIME_SOURCE)
protocore_requires(PROTOCORE_ENABLE_MDNS_ADAPTIVE PROTOCORE_ENABLE_MDNS)
protocore_requires(PROTOCORE_ENABLE_MDNS_ADAPTIVE PROTOCORE_ENABLE_PROMISC)
protocore_requires(PROTOCORE_ENABLE_FTP_SESSION PROTOCORE_ENABLE_FTP)
protocore_requires(PROTOCORE_ENABLE_EDGE_CACHE PROTOCORE_ENABLE_HTTP_CACHE)
protocore_requires(PROTOCORE_ENABLE_EDGE_CACHE PROTOCORE_ENABLE_HTTP_CLIENT)
protocore_requires(PROTOCORE_ENABLE_EDGE_MESH PROTOCORE_ENABLE_EDGE_CACHE)
protocore_requires(PROTOCORE_ENABLE_TLS_RESUMPTION PROTOCORE_ENABLE_TLS)
protocore_requires(PROTOCORE_ENABLE_METRICS PROTOCORE_ENABLE_STATS)
protocore_requires(PROTOCORE_ENABLE_SNMP_TRAP PROTOCORE_ENABLE_SNMP)
protocore_requires(PROTOCORE_ENABLE_PMBUS PROTOCORE_ENABLE_SMBUS)
protocore_requires(PROTOCORE_ENABLE_COAP_OBSERVE PROTOCORE_ENABLE_COAP)
protocore_requires(PROTOCORE_ENABLE_WS_DEFLATE PROTOCORE_ENABLE_WEBSOCKET)
protocore_requires(PROTOCORE_ENABLE_CIA402 PROTOCORE_ENABLE_CANOPEN)
protocore_requires(PROTOCORE_ENABLE_SSH_ZLIB PROTOCORE_ENABLE_SSH)
protocore_requires(PROTOCORE_ENABLE_SSH_KEYBOARD_INTERACTIVE PROTOCORE_ENABLE_SSH)
protocore_requires(PROTOCORE_ENABLE_SSH_SFTP PROTOCORE_ENABLE_SSH)
protocore_requires(PROTOCORE_ENABLE_SSH_SCP PROTOCORE_ENABLE_SSH)
protocore_requires(PROTOCORE_ENABLE_WEB_TERMINAL PROTOCORE_ENABLE_WEBSOCKET)
protocore_requires(PROTOCORE_ENABLE_DASHBOARD PROTOCORE_ENABLE_SSE)
protocore_requires(PROTOCORE_ENABLE_SNMP_V3 PROTOCORE_ENABLE_SNMP)
protocore_requires(PROTOCORE_ENABLE_OPCUA_CLIENT PROTOCORE_ENABLE_OPCUA)
protocore_requires(PROTOCORE_ENABLE_UMATI PROTOCORE_ENABLE_OPCUA)
protocore_requires(PROTOCORE_ENABLE_ROBOTICS PROTOCORE_ENABLE_OPCUA)
protocore_requires(PROTOCORE_ENABLE_EUROMAP77 PROTOCORE_ENABLE_OPCUA)
protocore_requires(PROTOCORE_ENABLE_CONFIG_IO PROTOCORE_ENABLE_CONFIG_STORE)

# The compiler sees every flag, so a source that selects an arm on one - and the Arduino shim,
# which selects nothing and compiles the lot - reads the same value the build decided.
foreach(_f IN ITEMS
    PROTOCORE_ENABLE_ACCEPT_THROTTLE
    PROTOCORE_ENABLE_AD9238
    PROTOCORE_ENABLE_ADS
    PROTOCORE_ENABLE_ADS1115
    PROTOCORE_ENABLE_AES256CTR
    PROTOCORE_ENABLE_AESGCM
    PROTOCORE_ENABLE_AES_BLOCK
    PROTOCORE_ENABLE_AES_CMAC
    PROTOCORE_ENABLE_AES_SBOX
    PROTOCORE_ENABLE_AMQP
    PROTOCORE_ENABLE_ATC
    PROTOCORE_ENABLE_AUDIT_LOG
    PROTOCORE_ENABLE_AUTH
    PROTOCORE_ENABLE_AUTH_LOCKOUT
    PROTOCORE_ENABLE_BACNET
    PROTOCORE_ENABLE_BASE64
    PROTOCORE_ENABLE_BIGNUM
    PROTOCORE_ENABLE_BLE_GATT
    PROTOCORE_ENABLE_BUS_CAPTURE
    PROTOCORE_ENABLE_C37118
    PROTOCORE_ENABLE_CANOPEN
    PROTOCORE_ENABLE_CBOR
    PROTOCORE_ENABLE_CC1101
    PROTOCORE_ENABLE_CCLINK
    PROTOCORE_ENABLE_CHACHA20
    PROTOCORE_ENABLE_CHACHAPOLY
    PROTOCORE_ENABLE_CIA402
    PROTOCORE_ENABLE_CIP
    PROTOCORE_ENABLE_CLOUDEVENTS
    PROTOCORE_ENABLE_COAP
    PROTOCORE_ENABLE_COAP_BLOCK
    PROTOCORE_ENABLE_COAP_OBSERVE
    PROTOCORE_ENABLE_CONFIG_IO
    PROTOCORE_ENABLE_CONFIG_STORE
    PROTOCORE_ENABLE_CONTROL
    PROTOCORE_ENABLE_COTP
    PROTOCORE_ENABLE_CSRF
    PROTOCORE_ENABLE_CT_EQ
    PROTOCORE_ENABLE_CURVE25519
    PROTOCORE_ENABLE_DASHBOARD
    PROTOCORE_ENABLE_DBM
    PROTOCORE_ENABLE_DDS
    PROTOCORE_ENABLE_DEFLATE_RFC1951
    PROTOCORE_ENABLE_DEVICENET
    PROTOCORE_ENABLE_DEVICE_ID
    PROTOCORE_ENABLE_DF1
    PROTOCORE_ENABLE_DIAG
    PROTOCORE_ENABLE_DIFFSERV
    PROTOCORE_ENABLE_DIRECTNET
    PROTOCORE_ENABLE_DMA
    PROTOCORE_ENABLE_DMX
    PROTOCORE_ENABLE_DNC
    PROTOCORE_ENABLE_DNP3
    PROTOCORE_ENABLE_DNS
    PROTOCORE_ENABLE_DNS_RESOLVER
    PROTOCORE_ENABLE_DNS_SERVER
    PROTOCORE_ENABLE_DOCSTORE
    PROTOCORE_ENABLE_DSHOT
    PROTOCORE_ENABLE_DTLS
    PROTOCORE_ENABLE_ECDSA
    PROTOCORE_ENABLE_ED25519
    PROTOCORE_ENABLE_EDGE_CACHE
    PROTOCORE_ENABLE_EDGE_MESH
    PROTOCORE_ENABLE_ENIP
    PROTOCORE_ENABLE_ENOCEAN
    PROTOCORE_ENABLE_ESPNOW
    PROTOCORE_ENABLE_ETAG
    PROTOCORE_ENABLE_ETHERNET
    PROTOCORE_ENABLE_EUROMAP77
    PROTOCORE_ENABLE_EXC_DECODER
    PROTOCORE_ENABLE_FAILSAFE
    PROTOCORE_ENABLE_FANUC_J519
    PROTOCORE_ENABLE_FDC2214
    PROTOCORE_ENABLE_FE25519
    PROTOCORE_ENABLE_FILE_SERVING
    PROTOCORE_ENABLE_FINS
    PROTOCORE_ENABLE_FLOW_EXPORT
    PROTOCORE_ENABLE_FOCAS
    PROTOCORE_ENABLE_FORWARD
    PROTOCORE_ENABLE_FORWARDED_TRUST
    PROTOCORE_ENABLE_FTP
    PROTOCORE_ENABLE_FTP_SESSION
    PROTOCORE_ENABLE_GATEWAY
    PROTOCORE_ENABLE_GHASH
    PROTOCORE_ENABLE_GOOSE
    PROTOCORE_ENABLE_GPIB
    PROTOCORE_ENABLE_GPIO_MAP
    PROTOCORE_ENABLE_GRAPHQL
    PROTOCORE_ENABLE_GRPC_WEB
    PROTOCORE_ENABLE_GUARDRAILS
    PROTOCORE_ENABLE_HAAS_MDC
    PROTOCORE_ENABLE_HAPPY_EYEBALLS
    PROTOCORE_ENABLE_HART
    PROTOCORE_ENABLE_HISLIP
    PROTOCORE_ENABLE_HMAC_SHA256
    PROTOCORE_ENABLE_HMAC_SHA512
    PROTOCORE_ENABLE_HMMD
    PROTOCORE_ENABLE_HOSTLINK
    PROTOCORE_ENABLE_HOTSWAP
    PROTOCORE_ENABLE_HTTP2
    PROTOCORE_ENABLE_HTTP3
    PROTOCORE_ENABLE_HTTP_CACHE
    PROTOCORE_ENABLE_HTTP_CLIENT
    PROTOCORE_ENABLE_HTTP_CLOCK
    PROTOCORE_ENABLE_HTTP_DELIVERY
    PROTOCORE_ENABLE_HTTP_PARSER
    PROTOCORE_ENABLE_HTTP_ROUTE
    PROTOCORE_ENABLE_HW_HEALTH
    PROTOCORE_ENABLE_ICCP
    PROTOCORE_ENABLE_IEC60870
    PROTOCORE_ENABLE_IFACE_BRIDGE
    PROTOCORE_ENABLE_IKEV2
    PROTOCORE_ENABLE_INA219
    PROTOCORE_ENABLE_INTERBUS
    PROTOCORE_ENABLE_IOLINK
    PROTOCORE_ENABLE_IPV6
    PROTOCORE_ENABLE_IP_ALLOWLIST
    PROTOCORE_ENABLE_J1939
    PROTOCORE_ENABLE_J2735
    PROTOCORE_ENABLE_JSON
    PROTOCORE_ENABLE_JWT
    PROTOCORE_ENABLE_KDF
    PROTOCORE_ENABLE_KEEPALIVE
    PROTOCORE_ENABLE_LD2410
    PROTOCORE_ENABLE_LDC1614
    PROTOCORE_ENABLE_LINK_MANAGER
    PROTOCORE_ENABLE_LOGBUF
    PROTOCORE_ENABLE_LONWORKS
    PROTOCORE_ENABLE_LORA
    PROTOCORE_ENABLE_LSV2
    PROTOCORE_ENABLE_LWM2M
    PROTOCORE_ENABLE_MBPLUS
    PROTOCORE_ENABLE_MBUS
    PROTOCORE_ENABLE_MD
    PROTOCORE_ENABLE_MDNS
    PROTOCORE_ENABLE_MDNS_ADAPTIVE
    PROTOCORE_ENABLE_MELSEC
    PROTOCORE_ENABLE_METRICS
    PROTOCORE_ENABLE_MMS
    PROTOCORE_ENABLE_MNT
    PROTOCORE_ENABLE_MODBUS
    PROTOCORE_ENABLE_MODBUS_MASTER
    PROTOCORE_ENABLE_MODBUS_RTU
    PROTOCORE_ENABLE_MPR121
    PROTOCORE_ENABLE_MQTT
    PROTOCORE_ENABLE_MQTT_SN
    PROTOCORE_ENABLE_MSGPACK
    PROTOCORE_ENABLE_MTCONNECT
    PROTOCORE_ENABLE_MULTIPART
    PROTOCORE_ENABLE_NATS
    PROTOCORE_ENABLE_NEMA_TS2
    PROTOCORE_ENABLE_NETADAPT
    PROTOCORE_ENABLE_NMEA0183
    PROTOCORE_ENABLE_NMEA2000
    PROTOCORE_ENABLE_NRF24
    PROTOCORE_ENABLE_NTCIP
    PROTOCORE_ENABLE_NTP
    PROTOCORE_ENABLE_NTP_SERVER
    PROTOCORE_ENABLE_NTRIP_CASTER
    PROTOCORE_ENABLE_NTS
    PROTOCORE_ENABLE_OAUTH2
    PROTOCORE_ENABLE_OBSERVABILITY
    PROTOCORE_ENABLE_OCIT
    PROTOCORE_ENABLE_OIDC
    PROTOCORE_ENABLE_OPCUA
    PROTOCORE_ENABLE_OPCUA_CLIENT
    PROTOCORE_ENABLE_OPENADR
    PROTOCORE_ENABLE_OTA
    PROTOCORE_ENABLE_OTA_ROLLBACK
    PROTOCORE_ENABLE_PACKML
    PROTOCORE_ENABLE_PARTITION_MONITOR
    PROTOCORE_ENABLE_PCA9685
    PROTOCORE_ENABLE_PER_IP_THROTTLE
    PROTOCORE_ENABLE_PMBUS
    PROTOCORE_ENABLE_PN532
    PROTOCORE_ENABLE_POLY1305
    PROTOCORE_ENABLE_POWERLINK
    PROTOCORE_ENABLE_POWER_MGMT
    PROTOCORE_ENABLE_PQC_KEX
    PROTOCORE_ENABLE_PREEMPT_QUEUE
    PROTOCORE_ENABLE_PROFIBUS
    PROTOCORE_ENABLE_PROFINET
    PROTOCORE_ENABLE_PROMISC
    PROTOCORE_ENABLE_PROTOBUF
    PROTOCORE_ENABLE_PROVISIONING
    PROTOCORE_ENABLE_PROXY_PROTOCOL
    PROTOCORE_ENABLE_PSRAM_POOL
    PROTOCORE_ENABLE_PTP
    PROTOCORE_ENABLE_RADIO_POWER
    PROTOCORE_ENABLE_RADIO_SNIFF
    PROTOCORE_ENABLE_RANGE
    PROTOCORE_ENABLE_RAWL2
    PROTOCORE_ENABLE_RAWMEMCPY
    PROTOCORE_ENABLE_RCWL0516
    PROTOCORE_ENABLE_REDIS
    PROTOCORE_ENABLE_RELAY
    PROTOCORE_ENABLE_RNG
    PROTOCORE_ENABLE_ROAMING
    PROTOCORE_ENABLE_ROBOTICS
    PROTOCORE_ENABLE_RSA
    PROTOCORE_ENABLE_RTC
    PROTOCORE_ENABLE_S7COMM
    PROTOCORE_ENABLE_SAFETY_SCL
    PROTOCORE_ENABLE_SCPI
    PROTOCORE_ENABLE_SDI12
    PROTOCORE_ENABLE_SEN0192
    PROTOCORE_ENABLE_SENML
    PROTOCORE_ENABLE_SEP2
    PROTOCORE_ENABLE_SERCOS
    PROTOCORE_ENABLE_SHA1
    PROTOCORE_ENABLE_SHA256
    PROTOCORE_ENABLE_SHA512
    PROTOCORE_ENABLE_SHT3X
    PROTOCORE_ENABLE_SIGFOX
    PROTOCORE_ENABLE_SIMATIC
    PROTOCORE_ENABLE_SLEEP_SCHED
    PROTOCORE_ENABLE_SMB
    PROTOCORE_ENABLE_SMBUS
    PROTOCORE_ENABLE_SMTP
    PROTOCORE_ENABLE_SNMP
    PROTOCORE_ENABLE_SNMP_TRAP
    PROTOCORE_ENABLE_SNMP_V3
    PROTOCORE_ENABLE_SNP
    PROTOCORE_ENABLE_SOCKPOOL
    PROTOCORE_ENABLE_SOUTHBOUND
    PROTOCORE_ENABLE_SPARKPLUG
    PROTOCORE_ENABLE_SPA_ROUTER
    PROTOCORE_ENABLE_SQLITE
    PROTOCORE_ENABLE_SSE
    PROTOCORE_ENABLE_SSH
    PROTOCORE_ENABLE_SSH_CLIENT
    PROTOCORE_ENABLE_SSH_KEYBOARD_INTERACTIVE
    PROTOCORE_ENABLE_SSH_RSA
    PROTOCORE_ENABLE_SSH_SCP
    PROTOCORE_ENABLE_SSH_SFTP
    PROTOCORE_ENABLE_SSH_ZLIB
    PROTOCORE_ENABLE_STATS
    PROTOCORE_ENABLE_STATSD
    PROTOCORE_ENABLE_STOMP
    PROTOCORE_ENABLE_SUNSPEC
    PROTOCORE_ENABLE_SYSLOG
    PROTOCORE_ENABLE_TCP
    PROTOCORE_ENABLE_TCP_CLIENT
    PROTOCORE_ENABLE_TELEMETRY
    PROTOCORE_ENABLE_TELNET
    PROTOCORE_ENABLE_THEMES
    PROTOCORE_ENABLE_THREAD
    PROTOCORE_ENABLE_TIME_SOURCE
    PROTOCORE_ENABLE_TLS
    PROTOCORE_ENABLE_TLS_POLICY
    PROTOCORE_ENABLE_TLS_RESUMPTION
    PROTOCORE_ENABLE_TLS_RPK
    PROTOCORE_ENABLE_TOTP
    PROTOCORE_ENABLE_TRACE_CAPTURE
    PROTOCORE_ENABLE_UBX
    PROTOCORE_ENABLE_UDP
    PROTOCORE_ENABLE_UDP_TELEMETRY
    PROTOCORE_ENABLE_UMATI
    PROTOCORE_ENABLE_UPLOAD
    PROTOCORE_ENABLE_UTMC
    PROTOCORE_ENABLE_VL53L0X
    PROTOCORE_ENABLE_VXI11
    PROTOCORE_ENABLE_WAL
    PROTOCORE_ENABLE_WAMP
    PROTOCORE_ENABLE_WAVE
    PROTOCORE_ENABLE_WEARLEVEL
    PROTOCORE_ENABLE_WEBDAV
    PROTOCORE_ENABLE_WEBHOOK
    PROTOCORE_ENABLE_WEBSOCKET
    PROTOCORE_ENABLE_WEB_ASSETS
    PROTOCORE_ENABLE_WEB_TERMINAL
    PROTOCORE_ENABLE_WIFI_SNIFFER
    PROTOCORE_ENABLE_WISUN
    PROTOCORE_ENABLE_WS_CLIENT
    PROTOCORE_ENABLE_WS_DEFLATE
    PROTOCORE_ENABLE_X509
    PROTOCORE_ENABLE_XMPP
    PROTOCORE_ENABLE_ZIGBEE
    PROTOCORE_ENABLE_ZWAVE
  )
  if(${_f})
    target_compile_definitions(pc_config INTERFACE ${_f}=1)
  else()
    target_compile_definitions(pc_config INTERFACE ${_f}=0)
  endif()
endforeach()
